### PR TITLE
Closes #2403: Save UUIDs when importing Quickstart config overrides to prevent deprecation warnings.

### LINKED ISSUE #2403: Deprecation warnings while running PHPunit tests
## Problem/Motivation
Deprecation warnings are generated when running our Quickstart PHPunit tests.

### Describe the bug
```
Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /app/web/core/lib/Drupal/Core/Config/Entity/Query/Condition.php on line 39

Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 220

Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 225
```

### To Reproduce
```
lando phpunit
```

## Proposed resolution
Find (and fix) the source of the deprecation warnings.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description

Updates `AZConfigOverride::importOverrides()` to include step to ensure UUIDs exist on imported config entities.

This should resolve issues we've seen with the following deprecation error showing up in various contexts for override configs:
```
Deprecated function: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\Core\Config\Entity\Query\Condition->compile() (line 39 of core/lib/Drupal/Core/Config/Entity/Query/Condition.php).
```

## Related issues

Closes #2403

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [x] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Comment by joeparsons** [comment]
Thanks to @tadean for consulting with me on this one.

A couple of potential things to still add to this based on conversations with him:

> - At that step, check if the current config has a uuid already, and if so, use that one rather than generating it
> - For sites that already have the issue, maybe that means we can do some kind of database update to add uuids to the affected entities or something? Not sure if that's a bad idea or not...

File: modules/custom/az_core/src/AZConfigOverride.php [hunk 1]
```diff
@@ -123,6 +123,10 @@ public function importOverrides(array $modules) {
             '@config_id' => $name,
           ]);
           $config = $this->configFactory->getEditable($name);
+          // Generate a UUID for the configuration if one doesn't exist.
+          if (!isset($data['uuid']) || empty($data['uuid'])) {
+            $data['uuid'] = \Drupal::service('uuid')->generate();
+          }
```
Comment (tadean) [inline modules/custom/az_core/src/AZConfigOverride.php:129]:
```suggestion
          // Generate a UUID for the configuration if one doesn't exist.
          $data['uuid'] = $config->get('uuid') ?? $data['uuid'] ?? \Drupal::service('uuid')->generate();  
```

File: modules/custom/az_core/src/AZConfigOverride.php [hunk 2]
```diff
@@ -123,6 +123,8 @@ public function importOverrides(array $modules) {
             '@config_id' => $name,
           ]);
           $config = $this->configFactory->getEditable($name);
+          // Generate a UUID for the configuration if one doesn't exist.
+          $data['uuid'] = $config->get('uuid') ?? $data['uuid'] ?? \Drupal::service('uuid')->generate();
```
Comment (joeparsons) [inline modules/custom/az_core/src/AZConfigOverride.php:127]:
```suggestion
          $data['uuid'] = $config->get('uuid') ?? $data['uuid'] ?? \Drupal::service('uuid')->generate();
```

**Comment by joeparsons** [comment]
Added update function:
```
 --------- -------------------------- ------------- -------------------------------------------------------------------- 
  Module    Update ID                  Type          Description                                                         
 --------- -------------------------- ------------- -------------------------------------------------------------------- 
  az_core   add_missing_config_uuids   post-update   Add missing UUIDs to existing Quickstart override config entities.  
 --------- -------------------------- ------------- -------------------------------------------------------------------- 


 ┌ Do you wish to run the specified pending updates? ───────────┐
 │ Yes                                                          │
 └──────────────────────────────────────────────────────────────┘

>  [notice] Update started: az_core_post_update_add_missing_config_uuids
>  [notice] Added missing UUID to search.page.node_search.
>  [notice] Added missing UUID to core.entity_form_display.node.az_event.default.
>  [notice] Added missing UUID to core.entity_form_display.node.az_flexible_page.default.
>  [notice] Added missing UUID to core.entity_form_display.node.az_news.default.
>  [notice] Added missing UUID to core.entity_form_display.node.az_person.default.
>  [notice] Added missing UUID to metatag.metatag_defaults.global.
>  [notice] Added missing UUID to metatag.metatag_defaults.node.
>  [notice] Update completed: az_core_post_update_add_missing_config_uuids
```

File: modules/custom/az_core/az_core.post_update.php [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+ * Post-update functions for AZ Core module.
+ */
+
+use Drupal\az_core\Plugin\ConfigProvider\QuickstartConfigProvider;
+
+/**
+ * Add missing UUIDs to existing Quickstart override config entities.
+ */
+function az_core_post_update_add_missing_config_uuids() {
+  // Get all QuicsktartConfigProvider config data.
```
Comment (bberndt-uaz) [inline modules/custom/az_core/az_core.post_update.php:14]:
```suggestion
  // Get all QuickstartConfigProvider config data.
```

**Review by bberndt-uaz — APPROVED** [review]
Nice! In Probo, I no longer see the errors when saving metatag default values.

**Review by trackleft — APPROVED** [review]

**Review by tadean — APPROVED** [review]
