### PR TITLE
Close #3210, Close #3037 Address failing PHPCS security and coding standards warnings.

### LINKED ISSUE #3037: Address PHPCodesniffer Warnings
### Condition of satisfaction

- [ ]  The 9 existing warnings are no longer triggered.

```
1..WW..W... 10 / 10 (100%)
2
3
4
5FILE: ...les/custom/az_quickstart/modules/custom/az_event/az_event.module
6----------------------------------------------------------------------
7FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
8----------------------------------------------------------------------
9 220 | WARNING | Line exceeds 80 characters; contains 82
10     |         | characters (Drupal.Files.LineLength.TooLong)
11----------------------------------------------------------------------
12
13
14FILE: ...z_quickstart/modules/custom/az_publication/az_publication.module
15----------------------------------------------------------------------
16FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
17----------------------------------------------------------------------
18 294 | WARNING | Weird usage of preg_replace, please check manually
19     |         | for /e modifier.
20     |         | (Security.BadFunctions.PregReplace.PregReplaceWeird)
21----------------------------------------------------------------------
22
23
24FILE: .../az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php
25----------------------------------------------------------------------
26FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
27----------------------------------------------------------------------
28 142 | WARNING | Function array_filter() that supports callback
29     |         | detected
30     |         | (Security.BadFunctions.CallbackFunctions.WarnCallbackFunctions)
31----------------------------------------------------------------------
32
33
34FILE: ...ication/az_publication_bibtex/src/Processor/AZLatexProcessor.php
35----------------------------------------------------------------------
36FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
37----------------------------------------------------------------------
38 392 | WARNING | Function array_walk_recursive() that supports
39     |         | callback detected
40     |         | (Security.BadFunctions.CallbackFunctions.WarnCallbackFunctions)
41 413 | WARNING | Dynamic usage of preg_replace, please check manually
42     |         | for /e modifier or user input.
43     |         | (Security.BadFunctions.PregReplace.PregReplaceDyn)
44----------------------------------------------------------------------
45
46
47FILE: ...ation/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php
48----------------------------------------------------------------------
49FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
50----------------------------------------------------------------------
51  7 | WARNING | Filesystem function file used but not as a
52    |         | function
53    |         | (Security.BadFunctions.FilesystemFunctions.WarnWeirdFilesystem)
54 72 | WARNING | Possible useless method overriding detected
55    |         | (Generic.CodeAnalysis.UselessOverridingMethod.Found)
56 87 | WARNING | Filesystem function realpath() detected with dynamic
57    |         | parameter
58    |         | (Security.BadFunctions.FilesystemFunctions.WarnFilesystem)
59----------------------------------------------------------------------
60
61
62FILE: ...lication_bibtex/src/Plugin/migrate_plus/data_parser/AZBibtex.php
63----------------------------------------------------------------------
64FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
65----------------------------------------------------------------------
66 44 | WARNING | Function array_filter() that supports callback
67    |         | detected
68    |         | (Security.BadFunctions.CallbackFunctions.WarnCallbackFunctions)
69----------------------------------------------------------------------
70
71Time: 881ms; Memory: 28MB
72```

### LINKED ISSUE #3210: Fix PHP_CodeSniffer coding standards warnings
Our Coding Standards Check is starting to be unwieldy with lots of issues.
```
..W.WW..W. 10 / 10 (100%)
2
3
4
5FILE: ...tom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.module
6--------------------------------------------------------------------------------
7FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
8--------------------------------------------------------------------------------
9  8 | WARNING | [x] Unused use statement
10    |         |     (Drupal.Classes.UnusedUseStatement.UnusedUse)
11  9 | WARNING | [x] Unused use statement
12    |         |     (Drupal.Classes.UnusedUseStatement.UnusedUse)
13 10 | WARNING | [x] Unused use statement
14    |         |     (Drupal.Classes.UnusedUseStatement.UnusedUse)
15--------------------------------------------------------------------------------
16PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
17--------------------------------------------------------------------------------
18
19
20FILE: .../web/profiles/custom/az_quickstart/modules/custom/az_event/az_event.module
21--------------------------------------------------------------------------------
22FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
23--------------------------------------------------------------------------------
24 220 | WARNING | Line exceeds 80 characters; contains 82 characters
25     |         | (Drupal.Files.LineLength.TooLong)
26--------------------------------------------------------------------------------
27
28
29FILE: ...s/custom/az_quickstart/modules/custom/az_publication/az_publication.module
30--------------------------------------------------------------------------------
31FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
32--------------------------------------------------------------------------------
33 314 | WARNING | Weird usage of preg_replace, please check manually for /e
34     |         | modifier.
35     |         | (Security.BadFunctions.PregReplace.PregReplaceWeird)
36--------------------------------------------------------------------------------
37
38
39FILE: ...om/az_publication/az_publication_bibtex/src/Processor/AZLatexProcessor.php
40--------------------------------------------------------------------------------
41FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
42--------------------------------------------------------------------------------
43 392 | WARNING | Function array_walk_recursive() that supports callback
44     |         | detected
45     |         | (Security.BadFunctions.CallbackFunctions.WarnCallbackFunctions)
46 413 | WARNING | Dynamic usage of preg_replace, please check manually for /e
47     |         | modifier or user input.
48     |         | (Security.BadFunctions.PregReplace.PregReplaceDyn)
49--------------------------------------------------------------------------------
50
51
52FILE: ...les/custom/az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php
53--------------------------------------------------------------------------------
54FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
55--------------------------------------------------------------------------------
56 142 | WARNING | Function array_filter() that supports callback detected
57     |         | (Security.BadFunctions.CallbackFunctions.WarnCallbackFunctions)
58--------------------------------------------------------------------------------
59
60
61FILE: .../az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php
62--------------------------------------------------------------------------------
63FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
64--------------------------------------------------------------------------------
65  7 | WARNING | Filesystem function file used but not as a function
66    |         | (Security.BadFunctions.FilesystemFunctions.WarnWeirdFilesystem)
67 72 | WARNING | Possible useless method overriding detected
68    |         | (Generic.CodeAnalysis.UselessOverridingMethod.Found)
69 87 | WARNING | Filesystem function realpath() detected with dynamic
70    |         | parameter
71    |         | (Security.BadFunctions.FilesystemFunctions.WarnFilesystem)
72--------------------------------------------------------------------------------
73
74
75FILE: ...ion/az_publication_bibtex/src/Plugin/migrate_plus/data_parser/AZBibtex.php
76--------------------------------------------------------------------------------
77FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
78--------------------------------------------------------------------------------
79 44 | WARNING | Function array_filter() that supports callback detected
80    |         | (Security.BadFunctions.CallbackFunctions.WarnCallbackFunctions)
81--------------------------------------------------------------------------------
82
83Time: 911ms; Memory: 28MB
```

## Conditions of satisfaction
There are no errors or notices in the "Run PHP_CodeSniffer coding standards checks" step

`lando phpcbf` will resolve some of the problems automatically.

### PR DESCRIPTION
**Pull request by trackleft**
## Description
In this PR 

I disable a few PHPCS checks:
- Security.BadFunctions.CallbackFunctions
- Security.BadFunctions.FilesystemFunctions
- Security.BadFunctions.PregReplace

I turn on fail on warning.

I remove all ignores for rules we aren't running.

Also:
I fixed all of the coding standards issues.

## Related issues
Closes #3210
Closes #3037 

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [x] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [x] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: modules/custom/az_publication/az_publication_bibtex/src/Processor/AZLatexProcessor.php [hunk 1]
```diff
@@ -389,11 +389,13 @@ public function __invoke(array $entry) {
 
       // Translate array.
       if (is_array($entry[$tag])) {
+        //phpcs:ignore Security.BadFunctions.CallbackFunctions.WarnCallbackFunctions
```
Comment (trackleft) [inline modules/custom/az_publication/az_publication_bibtex/src/Processor/AZLatexProcessor.php:392]:
```suggestion
```

File: modules/custom/az_publication/az_publication_bibtex/src/Processor/AZLatexProcessor.php [hunk 2]
```diff
@@ -410,6 +412,7 @@ public function __invoke(array $entry) {
    *   The deTeX-ified string.
    */
   private function detex($text) {
+    //phpcs:ignore Security.BadFunctions.PregReplace.PregReplaceDyn
```
Comment (trackleft) [inline modules/custom/az_publication/az_publication_bibtex/src/Processor/AZLatexProcessor.php:415]:
```suggestion
```

File: modules/custom/az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php [hunk 3]
```diff
@@ -84,6 +77,7 @@ public function submitForm(array &$form, FormStateInterface $form_state) {
       $file = File::load($fid);
       if (!empty($file)) {
         $uri = $file->getFileUri();
+        // phpcs:ignore Security.BadFunctions.FilesystemFunctions.WarnFilesystem
```
Comment (trackleft) [inline modules/custom/az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php:80]:
```suggestion
```

File: modules/custom/az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php [hunk 4]
```diff
@@ -4,6 +4,7 @@
 
 use Drupal\Core\Form\FormBase;
 use Drupal\Core\Form\FormStateInterface;
+//phpcs:ignore Security.BadFunctions.FilesystemFunctions.WarnWeirdFilesystem
```
Comment (trackleft) [inline modules/custom/az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php:7]:
```suggestion
```

File: modules/custom/az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php [hunk 5]
```diff
@@ -139,6 +139,7 @@ public function viewsFormSubmit(&$form, FormStateInterface $form_state) {
       // We invalidate the entity list cache for other views.
       $views_entity_table_info = $view->query->getEntityTableInfo();
       // Find the entity type used by the view.
+      //phpcs:ignore Security.BadFunctions.CallbackFunctions.WarnCallbackFunctions
```
Comment (trackleft) [inline modules/custom/az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php:142]:
```suggestion
```

**Review by tadean — APPROVED** [review]
