### PR TITLE
Closes #3396: Makes clickable cards more accessible

### LINKED ISSUE #3396: I want clickable cards to be more accessible
## Problem/Motivation
When viewing cards on this page, the "Learn more" links are not descriptive enough.
https://registrar.arizona.edu/faculty-staff-resources/room-course-scheduling/schedule-classes

### Describe the bug
Card link text field should be more helpful for the content owner.

### To Reproduce
1. Create a card with a link
2. Use screen reader to navigate to the clickable button
3. Observe link text that is redundant and not explicit

## Proposed resolution
1. Add help text and/or warning to the card link text field
4. Add link around the card title when using the stretched link

https://github.com/az-digital/az_quickstart/tree/issue/3396

### Expected behavior
When using a screen reader, link should have useful context.

## Additional context
Issue seen on both of these pages
- Initial page: https://registrar.arizona.edu/faculty-staff-resources/room-course-scheduling/schedule-classes
- Mockup with standard Quickstart cards: https://live-dana-qs2.pantheonsite.io/schedule-classes-title

### PR DESCRIPTION
**Pull request by danahertzberg**
## Description
This adds help text to card link title field to encourage best accessibility practices.

Formatting changes came through automatically. I'm not getting the link URL to render on the title `<a>` tag and could use some help there, please.

- [x] Determine best link url reference
- [x] Unpin probo build
- [x] Update URI to URL nomenclature @tadean 

## Related issues
Closes #3396

## How to test

1. Add cards to a flexible page
2. Ensure if card has a link and title fields completed, the card title should be linked as well
3. Ensure all formatting remains unchanged (excluding underline on card title hover)
4. Test non/clickable and title location settings

Probo build: https://57b6254c-c439-411f-b907-7c043d332c1e.probo.build/pages/card-decks

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [x] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [x] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 1]
```diff
@@ -239,6 +237,7 @@ public function viewElements(FieldItemListInterface $items, $langcode) {
           '#langcode' => $item->getLangcode(),
         ],
         '#link' => $link_render_array,
+        '#link_url' => $this->pathValidator->getUrlIfValid($item->link_uri ?? '<none>'),
```
Comment (joshuasosa) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:240]: link_url, should this be link_uri for the new twig variable? I haven't tried this yet, just looking.

Comment (danahertzberg) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:240]: Didn't work for me :(

Comment (joshuasosa) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:240]: Ok, I went to test and confirmed: this should be `#link_uri` instead of `#link_url`.

Also, it might be best to use what $link_render_array is using on line 137 just to make sure it's the same as the original rendered link.
That would change this line to:
`'#link_uri' => $link_url ?: Url::fromRoute('<none>'),`

**Review by joshuasosa — COMMENTED** [review]
Also need to add `'link_uri' => NULL,` in az_card.module's `az_card_theme`.

File: modules/custom/az_card/az_card.module [hunk 2]
```diff
@@ -10,9 +10,10 @@ use Drupal\Core\Routing\RouteMatchInterface;
 /**
  * Implements hook_help().
  */
-function az_card_help($route_name, RouteMatchInterface $route_match) {
+function az_card_help($route_name, RouteMatchInterface $route_match)
+{
```
Comment (danahertzberg) [inline modules/custom/az_card/az_card.module:14]:
```suggestion
function az_card_help($route_name, RouteMatchInterface $route_match) {
```

File: modules/custom/az_card/az_card.module [hunk 3]
```diff
@@ -10,9 +10,10 @@ use Drupal\Core\Routing\RouteMatchInterface;
...
   switch ($route_name) {
-    // Main module help for the az_card module.
+      // Main module help for the az_card module.
```
Comment (danahertzberg) [inline modules/custom/az_card/az_card.module:16]:
```suggestion
    // Main module help for the az_card module.
```

File: modules/custom/az_card/az_card.module [hunk 4]
```diff
@@ -26,7 +27,8 @@ function az_card_help($route_name, RouteMatchInterface $route_match) {
 /**
  * Implements hook_theme().
  */
-function az_card_theme($existing, $type, $theme, $path) {
+function az_card_theme($existing, $type, $theme, $path)
+{
```
Comment (danahertzberg) [inline modules/custom/az_card/az_card.module:31]:
```suggestion
function az_card_theme($existing, $type, $theme, $path) {
```

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 5]
```diff
@@ -22,7 +22,8 @@
  *   }
  * )
  */
-class AZCardDefaultFormatter extends FormatterBase implements ContainerFactoryPluginInterface {
+class AZCardDefaultFormatter extends FormatterBase implements ContainerFactoryPluginInterface
+{
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:26]:
```suggestion
class AZCardDefaultFormatter extends FormatterBase implements ContainerFactoryPluginInterface {
```

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 6]
```diff
@@ -48,7 +49,8 @@ class AZCardDefaultFormatter extends FormatterBase implements ContainerFactoryPl
   /**
    * {@inheritdoc}
    */
-  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
+  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition)
+  {
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:53]:
```suggestion
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
```

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 7]
```diff
@@ -65,14 +67,16 @@ public static function create(ContainerInterface $container, array $configuratio
   /**
    * {@inheritdoc}
    */
-  public static function defaultSettings() {
+  public static function defaultSettings()
+  {
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:71]:
```suggestion
  public static function defaultSettings() {
```

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 8]
```diff
@@ -65,14 +67,16 @@ public static function create(ContainerInterface $container, array $configuratio
...
     return ['interactive_links' => TRUE] + parent::defaultSettings();
   }
 
   /**
    * {@inheritdoc}
    */
-  public function settingsForm(array $form, FormStateInterface $form_state) {
+  public function settingsForm(array $form, FormStateInterface $form_state)
+  {
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:79]:
```suggestion
  public function settingsForm(array $form, FormStateInterface $form_state) {
```

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 9]
```diff
@@ -87,7 +91,8 @@ public function settingsForm(array $form, FormStateInterface $form_state) {
   /**
    * {@inheritdoc}
    */
-  public function settingsSummary() {
+  public function settingsSummary()
+  {
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:95]:
```suggestion
  public function settingsSummary() {
```

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 10]
```diff
@@ -101,7 +106,8 @@ public function settingsSummary() {
   /**
    * {@inheritdoc}
    */
-  public function viewElements(FieldItemListInterface $items, $langcode) {
+  public function viewElements(FieldItemListInterface $items, $langcode)
+  {
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:110]:
```suggestion
  public function viewElements(FieldItemListInterface $items, $langcode) {
```

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 11]
```diff
@@ -127,8 +133,7 @@ public function viewElements(FieldItemListInterface $items, $langcode) {
         if (str_starts_with($item->link_uri ?? '', '/' . PublicStream::basePath())) {
           // Link to public file: use fromUri() to get the URL.
           $link_url = Url::fromUri(urldecode('base:' . $item->link_uri));
-        }
-        else {
+        } else {
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:136]:
```suggestion
        }
        else {
```

File: modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php [hunk 12]
```diff
@@ -139,7 +139,7 @@ public function formElement(FieldItemListInterface $items, $delta, array $elemen
         '#type' => 'container',
         '#attributes' => [
           'class' =>
-            ['col-12', 'col-sm-6', 'col-md-6', 'col-lg-4', 'card-preview'],
+          ['col-12', 'col-sm-6', 'col-md-6', 'col-lg-4', 'card-preview'],
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php:142]:
```suggestion
            ['col-12', 'col-sm-6', 'col-md-6', 'col-lg-4', 'card-preview'],
```

File: modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php [hunk 13]
```diff
@@ -149,7 +149,8 @@ public function formElement(FieldItemListInterface $items, $delta, array $elemen
         '#title' => $item->title ?? '',
         '#body' => check_markup(
           $item->body ?? '',
-          $item->body_format ?? self::AZ_CARD_DEFAULT_TEXT_FORMAT),
+          $item->body_format ?? self::AZ_CARD_DEFAULT_TEXT_FORMAT
+        ),
```
Comment (danahertzberg) [inline modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php:153]:
```suggestion
          $item->body_format ?? self::AZ_CARD_DEFAULT_TEXT_FORMAT),
```

**Review by danahertzberg — COMMENTED** [review]
Remove formatting changes

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 14]
```diff
@@ -123,6 +123,7 @@ public function viewElements(FieldItemListInterface $items, $langcode) {
 
       // Link.
       $link_render_array = [];
+      $link_url = '<none>';
```
Comment (trackleft) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:126]:
```suggestion
      $link_url = '';
```

Comment (trackleft) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:126]:
```
$ mkdir -p /src
2$ cd /src
3$ cd /src/az-quickstart-scaffolding
4$ /src/az-quickstart-scaffolding/vendor/bin/phpstan analyse --configuration web/profiles/custom/az_quickstart/phpstan.neon web/profiles/custom/az_quickstart
5   0/219 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%  20/219 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   9%  40/219 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  18%  60/219 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  27%  80/219 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  36% 120/219 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  54% 140/219 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  63% 160/219 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░]  73% 180/219 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░]  82% 200/219 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  91% 219/219 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
6
7 ------ ----------------------------------------------------------------------------------- 
8  Line   modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php  
9 ------ ----------------------------------------------------------------------------------- 
10  240    Variable $link_url might not be defined.                                           
11 ------ ----------------------------------------------------------------------------------- 
12
13
14 [ERROR] Found 1 error                                                          
15
16$ exit

```

Comment (trackleft) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:126]: To resolve the error, you need to ensure that the variable $link_url is defined before it is used in the viewElements method. Currently, `$link_url` might not be defined if certain conditions are not met within the foreach loop. See if you can determine which conditions

You can initialize `$link_url` with a default value at the beginning of the loop to ensure it is always defined.

Comment (trackleft) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:126]: You can think of this as setting a default value for the variable before using it.

Comment (danahertzberg) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:126]: Have lines 241 and 126 match in terms of using `<non>` or `<nolink>` or `''`

Comment (danahertzberg) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:126]: @tadean Will investigate further

Comment (joshuasosa) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:126]: > To resolve the error, you need to ensure that the variable `$link_url` is defined before it is used in the viewElements method.
It was used fine before in viewElements without being initialized. See current line [125](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php#L125). But perhaps it passes ok with line 137 there due to it being locally set with a local either-or setup?

Since it's now being used outside that block (`if ($item->link_title || $item->link_uri)`), I think initializing as `$link_url = '';` would be appropriate, similar to how `$link_render_array = [];` is initialized as empty above it. Then your line 241 will use $link_url if there's anything, or use the `Url::fromRoute('<none>')` if not, meaning $link_url doesn't need to be none as well.

It could also be rearranged to initialize as `$link_url = Url::fromRoute('<none>')` and then set line 241 as just `$link_url`.

**Comment by danahertzberg** [comment]
Just received approval from @accesswatch in the DRC! 🙌

File: modules/custom/az_card/az_card.module [hunk 15]
```diff
@@ -35,6 +35,7 @@ function az_card_theme($existing, $type, $theme, $path) {
         'title' => NULL,
         'body' => NULL,
         'link' => NULL,
+        'link_uri' => NULL,
```
Comment (tadean) [inline modules/custom/az_card/az_card.module:38]: It seems like this theme variable might be used as an URL rather than an URI...

File: modules/custom/az_card/templates/az-card.html.twig [hunk 16]
```diff
@@ -9,6 +9,7 @@
  * - title: The title field of a card.
  * - body: The body field of a card.
  * - link: The link field on a card.
+ * - link_uri: The link URL field on a card.
```
Comment (tadean) [inline modules/custom/az_card/templates/az-card.html.twig:12]:
```suggestion
 * - link_uri: The link URL.
```

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 17]
```diff
@@ -123,6 +123,7 @@ public function viewElements(FieldItemListInterface $items, $langcode) {
 
       // Link.
       $link_render_array = [];
+      $link_url = '';
       if ($item->link_title || $item->link_uri) {
```
Comment (trackleft) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:127]: ## Difference Between URI and URL in Drupal

In Drupal, as in general web development, the terms URI (Uniform Resource Identifier) and URL (Uniform Resource Locator) are often used interchangeably, but they have distinct meanings and uses. Here’s an overview of the differences and how they are typically used in Drupal:

### URI (Uniform Resource Identifier)

- **Definition**: A URI is a string of characters used to identify a resource. It is a broader term that includes URLs.
- **Components**: A URI can contain a scheme, authority, path, query, and fragment. 
- **Example**: 
  - URL: `http://example.com/path?query#fragment`
  - File URI: `public://example.txt`

### URL (Uniform Resource Locator)

- **Definition**: A URL is a specific type of URI that provides the means to locate a resource by describing its primary access mechanism (e.g., its network location).
- **Components**: A URL typically includes the scheme (e.g., `http` or `https`), the authority (e.g., `example.com`), and the path to the resource.
- **Example**: `http://example.com/path?query#fragment`

### How They Are Used in Drupal

#### URI in Drupal
- **File URIs**: Drupal often uses URIs to refer to files. For example, `public://example.txt` or `private://example.txt`. These URIs are not URLs, but they identify resources in a way that Drupal understands and can manage.
- **Entity URIs**: Entities in Drupal, such as nodes, users, and terms, have URIs that identify them within the system. For example, `entity:node/1` refers to the node with ID 1.

#### URL in Drupal
- **Path Aliases**: Drupal uses URLs to provide human-readable paths to resources. For example, a node might have a URL like `http://example.com/node/1` or, more commonly with path aliases, `http://example.com/about-us`.
- **Linking**: URLs are used to create hyperlinks in content, menus, and other user interfaces. They point to specific locations on the web where resources can be accessed.

### Practical Examples

#### Using URIs
- **File System**: When managing files, you might see URIs like `public://myfile.txt`. Drupal knows to look in the public files directory for `myfile.txt`.
- **Entity References**: When programmatically referencing an entity, you might use URIs such as `entity:node/1`.

#### Using URLs
- **Linking to Content**: When you create a link to a piece of content, you use a URL like `/node/1` or `/about-us`.
- **Site Configuration**: In site settings, you might configure the base URL of your site, which Drupal uses to generate absolute URLs.

### Summary

- **URI**: A broader term used to identify a resource, which can be a URL or other identifier. In Drupal, URIs are often used for file paths and entity references.
- **URL**: A specific type of URI that provides the location of a resource. In Drupal, URLs are used for web addresses, linking, and navigation.

Understanding the distinction and appropriate use of URIs and URLs can help in managing resources and creating links within a Drupal site effectively.

File: modules/custom/az_card/az_card.module (hunk 15 above)
Comment (tadean) [inline modules/custom/az_card/az_card.module:38]:
```suggestion
        'link_url' => NULL,
```
It seems like this might be a URL rather than a URI.

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 18]
```diff
@@ -239,6 +238,7 @@ public function viewElements(FieldItemListInterface $items, $langcode) {
           '#langcode' => $item->getLangcode(),
         ],
         '#link' => $link_render_array,
+        '#link_uri' => $link_url,
```
Comment (tadean) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:241]:
```suggestion
        '#link_url' => $link_url,
```
Potentially update to suggest this is an URL rather than a URI.

File: modules/custom/az_card/templates/az-card.html.twig (hunk 16 above)
Comment (tadean) [inline modules/custom/az_card/templates/az-card.html.twig:12]:
```suggestion
 * - link_url: The link URL only.
```

File: modules/custom/az_card/templates/az-card.html.twig [hunk 19]
```diff
@@ -26,7 +27,13 @@
       {{ media }}
       {% if title and title_style == 'title-on-image' %}
         <div class="card-img-overlay p-0 d-flex flex-column">
-          <{{ title_level }} class="bold mt-auto card-title bg-gradient-black text-white mb-0 p-card pt-8 {{ title_alignment }} {{ title_display }}">{{ title }}</{{ title_level }}>
+          <{{ title_level }} class="bold mt-auto card-title bg-gradient-black text-white mb-0 p-card pt-8 {{ title_alignment }} {{ title_display }}">
+            {% if link|render %}
+              <a href="{{ link_uri }}">{{ title }}</a>
```
Comment (tadean) [inline modules/custom/az_card/templates/az-card.html.twig:32]:
```suggestion
              <a href="{{ link_url }}">{{ title }}</a>
```

File: modules/custom/az_card/templates/az-card.html.twig [hunk 20]
```diff
@@ -40,7 +47,13 @@
   {% else %}
     <div class="card-body d-flex flex-column">
       {% if title and title_style == 'default' %}
-        <{{ title_level }} class="bold mt-0 mb-3 card-title {{ title_alignment }} {{ title_display }}">{{ title }}</{{ title_level }}>
+        <{{ title_level }} class="bold mt-0 mb-3 card-title {{ title_alignment }} {{ title_display }}">
+          {% if link|render %}
+            <a href="{{ link_uri }}">{{ title }}</a>
```
Comment (tadean) [inline modules/custom/az_card/templates/az-card.html.twig:52]:
```suggestion
            <a href="{{ link_url }}">{{ title }}</a>
```

**Review by tadean — COMMENTED** [review]
Added some code suggestions to indicate that the new theme variable is potentially a URL, rather than a URI.

**Review by joshuasosa — APPROVED** [review]
Tested on Probo and it works well! I think I would be good with this PR as it is.

I am wondering though if titles should get default underlines to visually indicate that they're links.

image
For example, in this test, you wouldn't be able to guess that the Test 1 text is clickable and Test 2 text isn't. It's also unclear that Test 3 is a whole clickable card.

**Comment by danahertzberg** [comment]
> I am wondering though if titles should get default underlines to visually indicate that they're links.
> For example, in this test, you wouldn't be able to guess that the Test 1 text is clickable and Test 2 text isn't. It's also unclear that Test 3 is a whole clickable card.

Thanks @joshuasosa! I think these are great considerations. The clickable cards do get a shadow to make them (barely) visually different from non-clickable cards. 

On non-clickable cards, if there is a link then the title does get an underline on hover. I'd love to learn more about what's needed from the visual standpoint. In this case, should we follow the two distinguishers rule like text links? A follow up ticket would be lovely. :)

**Comment by accesswatch** [comment]
I think they should as do other link text, right?

From: Dana Hertzberg ***@***.***>
Sent: Monday, June 24, 2024 1:35 PM
To: az-digital/az_quickstart ***@***.***>
Cc: Bishop, Jeff - (jeffbis) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [az-digital/az_quickstart] Closes #3396: Makes clickable cards more accessible (PR #3463)


External Email

________________________________
I am wondering though if titles should get default underlines to visually indicate that they're links.
For example, in this test, you wouldn't be able to guess that the Test 1 text is clickable and Test 2 text isn't. It's also unclear that Test 3 is a whole clickable card.

Thanks @joshuasosa<https://github.com/joshuasosa>! I think these are great considerations. The clickable cards do get a shadow to make them (barely) visually different from non-clickable cards.

On non-clickable cards, if there is a link then the title does get an underline on hover. I'd love to learn more about what's needed from the visual standpoint. In this case, should we follow the two distinguishers rule like text links? A follow up ticket would be lovely. :)

**Review by tadean — APPROVED** [review]

**Review by sanjanans — APPROVED** [review]

**Comment by danahertzberg** [comment]
Heading links follow up issue: https://github.com/az-digital/az_quickstart/issues/3504
