### PR TITLE
Closes #1128: Migration improvements for source paragraph items containing field collections.

### LINKED ISSUE #1128: Card deck paragraph migration plugin doesn't work consistently
## Problem/Motivation
The [az_paragraph_card_deck](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml) migration does not always work.

### Describe the bug
The `az_paragraph_card_deck` migration plugin seems to only work when the photos field is populated in the source.

### To Reproduce

1. Setup a local Quickstart site in lando
2. Enable `az_migration` module
3. Setup a D7 Quickstart 1 site with demo content installed to use as migration source
4. Run `drush mim --group az_migration`
5. Notice that only one of the card decks on the migrated version of this page was imported correctly: https://kitten.ltrr.arizona.edu/pages/uaqs-flexible-page-2

## Proposed resolution
Investigate & fix

### Expected behavior
Card deck migration plugin should work consistently.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
- Fairly significant refactoring to `AZParagraphsItem` migration source plugin (which adds field collection data to source paragraph items)
- Simplified `ParagraphsUpdateMediaCaption` migration process plugin
- Removed `ParagraphsMapFieldPropertyValue` migration process plugin and replaced usage with core migration process plugin chains
- Fixes issues that were preventing card deck paragraphs from importing correctly

## Related Issue
#1128 

## How Has This Been Tested?

Locally with lando

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joeparsons** [comment]
@tadean Is going to look into whether card order can be preserved.

File: modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php [hunk 1]
```diff
@@ -73,21 +73,24 @@ public function prepareRow(Row $row) {
...
-              $field_collection_value_item['delta'] = $i;
-              $field_collection_field_values[] = $field_collection_value_item;
-              $i++;
+              $field_collection_field_values[$delta]['delta'] = $delta;
+              $field_collection_field_values[$delta][$field_collection_field_name][] = $field_collection_value_item;
             }
           }
-          $row->setSourceProperty($field_collection_field_name, $field_collection_field_values);
         }
+        $source_property_name = $field . '_values';
```
Comment (tadean) [inline modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php:91]:
```suggestion
        ksort($field_collection_field_values);
        $source_property_name = $field . '_values';
```

Comment (tadean) [reply modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php:91]: For some reason it seems to matter more to the field plugin that the values be in order than the delta value. It seems to refuse to honor the delta value if it doesn't match the order the array is in...

**Review by tadean — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]
Cards appear in order on the migration site

**Comment by joeparsons** [comment]
Follow-up task: Add example code to media caption migration process plugin

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml [hunk 2]
```diff
@@ -17,46 +17,71 @@ destination:
...
+            - 0
+            - value
+      body_format:
+        plugin: default_value
+        default_value: az_standard
+      link_title:
+        -
+          plugin: skip_on_empty
+          method: process
+          source: field_uaqs_links
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml:51]: I think we should add something to the README.md  for this migration that says we are only migrating the first link. If there are multiple links on a card, they can edit the migrated card after the migration, to add the links to the text area as HTML instead of using the link field.

**Review by trackleft — APPROVED** [review]
