### PR TITLE
Closes #1517 Add flexible block migration

### LINKED ISSUE #1517: Add Flexible Block Migration
## Problem/Motivation
Blocks are becoming more prevalent and having them at least migrate, but not placed would be helpful.

### Describe the bug
Blocks are not migrating

### To Reproduce
Any migration

## Proposed resolution
Update migration GH Action to include migration of blocks

### Expected behavior

Ideally, blocks would migrate and be placed in correct nodes, but just migrating them would be helpful.

##  Screenshots
If applicable, add screenshots to help explain your problem. (Need a tool to share screenshots or screencasts as URLs? Try [monosnap](https://monosnap.com)

## Additional context

Possible source plugin for flexible block.

```php
<?php

namespace Drupal\az_migration\Plugin\migrate\source;

use Drupal\Core\Database\Driver\mysql\Connection as MySqlConnection;
use Drupal\migrate\Row;
use Drupal\migrate_drupal\Plugin\migrate\source\d7\FieldableEntity;

/**
 * Migration source plugin for Bean entities.
 *
 * @MigrateSource(
 *   id = "az_bean",
 *   source_module = "bean"
 * )
 */
class Bean extends FieldableEntity {

  /**
   * {@inheritdoc}
   */
  public function query() {
    $query = $this->select('bean_revision', 'br')
      ->fields('b', [
        'bid',
        'delta',
        'type',
        'uid',
      ])
      ->fields('br', [
        'vid',
        'label',
        'title',
        'view_mode',
        'data',
        'created',
        'changed',
        'log',
      ]);
    if ($this->getDatabase()->schema()->fieldExists('bean', 'uuid')) {
      $query->addField('b', 'uuid');
    }
    $query->addField('br', 'uid', 'revision_uid');
    $query->join('bean', 'b', 'b.bid = br.bid');
    $query->orderBy('br.vid', 'ASC');
    // A newer revision of a bean content entity isn't always the default
    // revision - so we compute this by comparing the version IDs found in the
    // "bean" and "bean_revision" tables. We will re-use this as "status".
    $cast_type = $this->getDatabase() instanceof MySqlConnection
      ? 'UNSIGNED INTEGER'
      : 'INTEGER';
    $status_expression = "CAST(b.vid >= br.vid AS $cast_type)";
    $query->addExpression($status_expression, 'revision_default');
    $query->addExpression($status_expression, 'status');

    if ($type = $this->configuration['type'] ?? NULL) {
      $query->condition('b.type', $type);
    }

    // We might have a type label, but nothing guarantees that every type has a
    // record in the "bean_type" table.
    if ($this->getDatabase()->schema()->tableExists('bean_type')) {
      $query->leftJoin('bean_type', 'bt', 'bt.name = b.type');
      $query->addField('bt', 'label', 'type_label');
    }

    // Get any entity translation revision data.
    if ($this->moduleExists('entity_translation')) {
      $query->leftJoin(
        'entity_translation_revision',
        'etr',
        'br.bid = etr.entity_id AND br.vid = etr.revision_id AND etr.entity_type = :entity_type',
        [
          ':entity_type' => 'bean',
        ]);
      $query->fields('etr', [
        'entity_id',
        'revision_id',
        'language',
        // If "translate" here is '1', it means that the current translation is
        // outdated.
        'translate',
      ]);
      $query->addField('etr', 'uid', 'etr_uid');
      $query->addField('etr', 'status', 'etr_status');
      $query->addField('etr', 'created', 'etr_created');
      $query->addField('etr', 'changed', 'etr_changed');
      $query->addField('etr', 'source', 'source_language');

      // Rows with empty source language are representing the default
      // translation.
      $query->orderBy('etr.revision_id', 'ASC');
      $query->orderBy('etr.source', 'ASC');
    }

    return $query;
  }

  /**
   * {@inheritdoc}
   */
  public function prepareRow(Row $row) {
    [
      'type' => $type,
      'bid' => $bean_id,
      'vid' => $revision_id,
    ] = $row->getSource();

    // Get Field API field values.
    $language_code = $row->getSourceProperty('language');
    foreach ($this->getFields('bean', $type) as $field_name => $field) {
      $row->setSourceProperty($field_name, $this->getFieldValues('bean', $field_name, $bean_id, $revision_id, $language_code));
    }

    // The "language" property is one of the IDs, so it always needs a value.
    if ($language_code === NULL) {
      $row->setSourceProperty('language', 'und');
    }

    return parent::prepareRow($row);
  }

  /**
   * {@inheritdoc}
   */
  public function fields() {
    return [
      'bid' => $this->t('The ID of the bean entity.'),
      'vid' => $this->t('The revision ID.'),
      'delta' => $this->t('The delta.'),
      'label' => $this->t('The administrative label.'),
      'title' => $this->t('The human label (title).'),
      'type' => $this->t('The bundle (type) of the bean.'),
      'view_mode' => $this->t('The view mode.'),
      'data' => $this->t('Additional data (a nested array which usually contains the view mode).'),
      'uid' => $this->t("The ID of the user who owns the bean's default revision"),
      'created' => $this->t('The time when the bean entity was created, as a Unix timestamp.'),
      'changed' => $this->t('The Unix timestamp when the revision was changed.'),
      'log' => $this->t('The revision log message.'),
      'status' => $this->t('The status (the published state) of the revision.'),
      'revision_default' => $this->t('Whether the revision is a default revision.'),
      'revision_uid' => $this->t('The ID of the user who created the revision.'),
      'language' => $this->t('The language code of the bean revision translation.'),
      'translate' => $this->t('Whether the current revision translation is outdated.'),
      'etr_uid' => $this->t('The ID of the user who created this revision translation.'),
      'etr_status' => $this->t('The status of this revision translation.'),
      'etr_created' => $this->t('Time when this revision translation was created.'),
      'etr_changed' => $this->t('Time when this revision translation was updated.'),
      'source_language' => $this->t('The source language of this revision translation.'),
      'uuid' => $this->t('The UUID of the bean entity if bean_uuid is enabled on source'),
      'type_label' => $this->t('Label of the bean type, if available.'),
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getIds() {
    $ids = [
      'bid' => [
        'type' => 'integer',
        'alias' => 'br',
      ],
      'vid' => [
        'type' => 'integer',
        'alias' => 'br',
      ],
    ];
    if ($this->moduleExists('entity_translation')) {
      $ids['language'] = [
        'type' => 'string',
      ];
    }

    return $ids;
  }

}
```
Check this migration for inspiration:
https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/migrations/migrate_plus.migration.az_node_flexible_page.yml

### PR DESCRIPTION
**Pull request by trackleft**
## Related issues

Closes #1517 

## How to test

1. Add diff for this PR as a composer patch to a Quickstart 2 site
2. Try running `migrate:import` on the `az_migration` migration group using a Quickstart 1 source site containing flexible blocks
3. Verify flexible blocks were migrated

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- **Minor release changes**
   - [x] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php [hunk 1]
```diff
@@ -281,6 +296,25 @@ public function transform($value, MigrateExecutableInterface $migrate_executable
 
           break;
 
+        // Embedded bean. Special consideration, as we need to know which
+        // migration the bean is part of, if any. Migration of an Embedded
+        // bean only is defined if it's a type that can be migrated.
+        case 'bean':
+          // Lookup of bean type.
+          $bean_type = Database::getConnection('migrate')
```
Comment (trackleft) [inline modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php:304]:
```suggestion
          $bean_type = Database::getConnection('default', 'migrate')
```

File: modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php [hunk 2]
```diff
@@ -281,6 +296,25 @@ public function transform($value, MigrateExecutableInterface $migrate_executable
...
+            // Map our D7 node type to a migration. If we can't, we have no
+            // guarantee our node is a migrated one.
+            if (!empty($migrations[$bean_type])) {
+              $migration = $migrations[$bean_type];
+              $post = $this->updateEmbedTag($id, 'block_content', 'drupal-entity', $view, $dom, $element, $migration, 'block_content');
+            }
+
+          }
+
+          break;
```
Comment (joeparsons) [inline modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php:317]:
```suggestion
          break;

```

File: modules/custom/az_migration/src/Plugin/migrate/source/AZBean.php [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+ */
+class AZBean extends FieldableEntity {
+
+  /**
+   * The join options between the bean and the bean_revisions table.
+   */
+  const JOIN = '[b].[vid] = [br].[vid]';
+
+
+
```
Comment (joeparsons) [inline modules/custom/az_migration/src/Plugin/migrate/source/AZBean.php:25]:
```suggestion
  const JOIN = '[b].[vid] = [br].[vid]';

```

File: modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php [hunk 4]
```diff
@@ -281,6 +297,26 @@ public function transform($value, MigrateExecutableInterface $migrate_executable
...
+        // migration the bean is part of, if any. Migration of an Embedded
+        // bean only is defined if it's a type that can be migrated.
+        case 'bean':
+          // Lookup of bean type.
+          $bean_type = Database::getConnection('default', 'migrate')
+            ->query('SELECT type FROM {bean} WHERE bid = :bid', [':bid' => $id])
+            ->fetchField();
+          if (!empty($bean_type)) {
+            // Map our D7 node type to a migration. If we can't, we have no
+            // guarantee our node is a migrated one.
```
Comment (trackleft) [inline modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php:310]:
```suggestion
          if (!empty($bean_type)) {
            // Map our D7 bean type to a migration. If we can't, we have no
            // guarantee our bean is a migrated one.
```

**Review by akslay — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]
