### PR TITLE
Closes #1248: Fix undefined index notices generated for existing cards.

### LINKED ISSUE #1248: Clickable Card PHP Notice (undefined index)
### Describe the bug
After updating a Quickstart 2 site to v2.0.15, the following PHP notice is printed in the site's logs for every card on the page you are viewing (that is not clickable). For example, if the page you are viewing has 3 non-clickable cards, you will see 3 notices in the log.

```
Notice: Undefined index: card_clickable in Drupal\az_card\Plugin\Field\FieldFormatter\AZCardDefaultFormatter->viewElements() (line 139 of /code/web/profiles/custom/az_quickstart/modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php)
```

The error might be stemming from non-clickable card decks that existed before the clickable card functionality was added? 
Chris thinks we might need to add this to the [formatter](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php#L143):
```if (isset($card_defaults['card_clickable']) && $card_defaults['card_clickable'] === 1) {```

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Should fix undefined index notices being generated on sites with existing cards after updating to 2.0.15.

## Related Issue
Closes #1248 
Issue introduced with #1220

## How Has This Been Tested?
Needs to be tested.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 1]
```diff
@@ -140,7 +140,7 @@ public function viewElements(FieldItemListInterface $items, $langcode) {
           if (!empty($parent_config['az_cards_paragraph_behavior'])) {
             $card_defaults = $parent_config['az_cards_paragraph_behavior'];
             // Is the card clickable?
-            if ($card_defaults['card_clickable']) {
+            if (isset($card_defaults['card_clickable'] && $card_defaults['card_clickable'] === TRUE) {
```
Comment (trackleft) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:143]:
```suggestion
            if (isset($card_defaults['card_clickable']) && $card_defaults['card_clickable'] === TRUE) {
```

Comment (trackleft) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:143]: I thought checkboxes always returned a `1` or `0` unless there was a schema

Comment (joeparsons) [reply modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:143]: Oops.  Thanks!

**Comment by akslay** [comment]
I created a multi-dev to test the patch against the site where I was noticing the problem. And it looks like the patch fixes the PHP notices but also introduces a new problem. Once you apply the patch, the "clickable" functionality stops working and you can only click on the physical button/link that's inside the card.

**Comment by trackleft** [comment]
Here is what it looks like in the DB 
image

**Comment by trackleft** [comment]
FYI @akslay now that you've confirmed that this PR stops the unidentified index notices, you shouldn't have to test on an existing codebase with the updated code.

**Comment by akslay** [comment]
Tested the updated patch on clickable and non-clickable cards and everything looks good to go this time. (:

**Review by akslay — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Review by tadean — APPROVED** [review]

File: modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php [hunk 2]
```diff
@@ -140,7 +140,7 @@ public function viewElements(FieldItemListInterface $items, $langcode) {
           if (!empty($parent_config['az_cards_paragraph_behavior'])) {
             $card_defaults = $parent_config['az_cards_paragraph_behavior'];
             // Is the card clickable?
-            if ($card_defaults['card_clickable']) {
+            if (isset($card_defaults['card_clickable']) && $card_defaults['card_clickable'] != FALSE) {
```
Comment (joeparsons) [inline modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php:143]: Changing this back to the way it was for truthy testing to remove the PHPCS warning since @akslay checked the PHP docs:
>When converting to bool, the following values are considered false:
>the empty string, and the string "0"
https://www.php.net/manual/en/types.comparisons.php

```suggestion
            if (isset($card_defaults['card_clickable']) && $card_defaults['card_clickable']) {
```

**Review by trackleft — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Review by akslay — APPROVED** [review]
