### PR TITLE
Closes #2845: Ensure legacy Quickstart block_content view is replaced by core view.

### LINKED ISSUE #2485: Determine best path forward for screen reader text for block titles.
## What is the problem that we want to solve?
Sometimes block titles are marked as "Do not display title"
image

## Conditions of satisfaction
- [ ] DRC signs off on any approach suggested.

### LINKED ISSUE #2845: Duplicate Blocks tabs on the Admin Content page
## Problem/Motivation
There are two Blocks tabs on the Admin Content page at /admin/content. The first Blocks tab links to /admin/content/block and displays a view without any sorting or filtering functionality. The second Blocks tab links to /admin/content/blocks and includes sorting and filtering.

### To Reproduce
Visit the page at /admin/content and observe the duplicate tabs.

## Proposed resolution
Joe found that the Drupal core block content view **does** include the sorting and filtering functionality. There may be an issue with the custom block content view that we installed in this pull request:

- [Include a blocks tab within content admin page options](https://github.com/az-digital/az_quickstart/pull/645)

With the update to Drupal 10.1, we removed the custom block content view that we had previously added:

- [Upgrade Drupal core to 10.1.x](https://github.com/az-digital/az_quickstart/pull/2587)

However, there is some additional cleanup we can do to complete the removal of our custom view.

### Expected behavior

Only one Blocks tab should be displayed on the Admin Content page. The tab should link to a page that allows users to sort and filter custom blocks.

#### First Blocks tab at /admin/content/block
image

#### Second Blocks tab at /admin/content/blocks
image

#### Example of a site with additional tabs
image

## Additional context

- [Block content view in the Drupal core block_content module](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/block_content/config/optional/views.view.block_content.yml)
- [Post update functions for the Drupal core block_content module](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/block_content/block_content.post_update.php)

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
- Removes menu local action associated with the removed legacy Quicsktart block_content view (replaced by the core version updated in Drupal core 10.1)
- Adds post update to force import of core view to ensure Quickstart view is replaced

## Related issues
Closes #2485

## How to test

This PR branch needs to be applied to an existing site DB to be able to test the DB update.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: az_quickstart.post_update.php [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+use Drupal\Core\Config\FileStorage;
+use Drupal\Core\Entity\EntityStorageException;
+
+/**
+ * Force import of core block_content view.
+ *
+ * Ensure legacy Quickstart block_content view is replaced with the Drupal core
+ * version updated in 10.1.x.
+ */
+function az_quicsktart_post_update_force_import_core_block_view(&$sandbox) {
```
Comment (tadean) [inline az_quickstart.post_update.php:17]:
```suggestion
function az_quickstart_post_update_force_import_core_block_view(&$sandbox) {
```

File: az_quickstart.post_update.php [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+  $config_to_import = 'views.view.block_content';
+  $module_path = \Drupal::service('extension.list.module')->getPath('block_content');
+  $config_storage = new FileStorage($module_path . '/config/optional');
+  $entity_type = \Drupal::service('config.manager')->getEntityTypeIdByName($config_to_import);
+  $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
```
Comment (tadean) [inline az_quickstart.post_update.php:22]:
```suggestion
  $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
  $id = $storage->getIDFromConfigName($config_to_import, $storage->getEntityType()->getConfigPrefix());
  $active = $storage->load($id);
```

File: az_quickstart.post_update.php [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  $config_record = $config_storage->read($config_to_import);
+
+  try {
+    /** @var \Drupal\Core\Config\Entity\ConfigEntityStorageInterface $storage */
+    $entity = $storage->createFromStorageRecord($config_record);
```
[the remark this answers is not in the document]
Comment (tadean) [reply az_quickstart.post_update.php:27]: This seems necessary to prevent `[notice] 'view' entity with ID 'block_content' already exists.`

File: az_quickstart.post_update.php (hunk 1 above)
Comment (joeparsons) [reply az_quickstart.post_update.php:17]: 🤦🏻‍♂️ Thanks.

File: az_quickstart.post_update.php [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+ *
+ * Ensure legacy Quickstart block_content view is replaced with the Drupal core
+ * version updated in 10.1.x.
+ */
+function az_quickstart_post_update_force_import_core_block_view(&$sandbox) {
+  $config_to_import = 'views.view.block_content';
+  $module_path = \Drupal::service('extension.list.module')->getPath('block_content');
+  $config_storage = new FileStorage($module_path . '/config/optional');
+  $entity_type = \Drupal::service('config.manager')->getEntityTypeIdByName($config_to_import);
+  $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
```
Comment (joeparsons) [inline az_quickstart.post_update.php:22]:
```suggestion
  /** @var \Drupal\Core\Config\Entity\ConfigEntityStorageInterface $storage */
  $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
```

**Comment by joeparsons** [comment]
Applied this update on a development version of the quickstart.arizona.edu site here:
https://blockview4-azs-quickstart.pantheonsite.io/

Verified that the post update ran as expected:
```
Run terminus drush azs-quickstart.blockview4 -- updb -y
Warning: ] This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
Warning: Permanently added '[appserver.blockview4.4344f5a7-ed97-4d75-9ed1-c35f25227592.drush.in]:2222' (RSA) to the list of known hosts.
 ------------------ ----------- --------------- -------------------------------- 
  Module             Update ID   Type            Description                     
 ------------------ ----------- --------------- -------------------------------- 
  system             10100       hook_update_n   10100 - Remove the year 2038    
                                                 date limitation.                
  az_event_trellis   1020801     hook_update_n   1020801 - Ensure                
                                                 views_remote_data module is     
                                                 installed.                      
  az_quickstart      1020801     hook_update_n   1020801 - Ensure ckeditor5      
                                                 module is installed.            
  az_quickstart      1020802     hook_update_n   1020802 - Enable extlink        
                                                 module by default.              
  blazy              82[17](https://github.com/uaz-web/team-tools/actions/runs/6579546880/job/17875925987#step:6:18)        hook_update_n   8217 - Matching a more          
                                                 relevant module version.        
  block_content      10100       hook_update_n   10100 - Update entity           
                                                 definition to handle revision   
                                                 routes.                         
  block_content      10200       hook_update_n   10200 - Remove the unique       
                                                 values constraint from block    
                                                 content info fields.            
  ckeditor_bs_grid   9001        hook_update_n   9001 - Rebuild caches to        
                                                 recognize plugin changes.       
  dblog              10100       hook_update_n   10100 - Remove the year 2038    
                                                 date limitation.                
  dblog              10101       hook_update_n   10101 - Converts the 'wid' of   
                                                 the 'watchdog' table to a big   
                                                 integer.                        
  history            10100       hook_update_n   10100 - Remove the year 2038    
                                                 date limitation.                
  honeypot           8101        hook_update_n   8101 - Corrects a               
                                                 sometimes-missing 'hostname'    
                                                 column in the {honeypot_user}   
                                                 table.                          
  honeypot           8102        hook_update_n   8102 - Creates an 'id' column   
                                                 for the {honeypot_user} table   
                                                 to act as a primary key.        
  migrate            10100       hook_update_n   10100 - Remove the year 2038    
                                                 date limitation.                
  redirect           8109        hook_update_n   8109 - Enable reset button for  
                                                 Redirect View.                  
  slick              8210        hook_update_n   8210 - Matching a more          
                                                 relevant module version.        
  az_quickstart      force_im    post-update     Force import of core            
                     port_cor                    block_content view.   Ensure    
                     e_block_                    legacy Quickstart               
                     view                        block_content view is replaced  
                                                 with the Drupal core  version   
                                                 updated in 10.1.x.              
  blazy              added_bl    post-update     Added a new Blazy Media         
                     azy_medi                    service.                        
                     a_servic                                                    
                     e                                                           
  blazy              added_fo    post-update     Added a new Blazy Grid          
                     rmatter_                    formatter for                   
                     blazy_en                    entityreferences.               
                     tity                                                        
  block_content      block_li    post-update     Update block_content 'block     
                     brary_vi                    library' view permission.       
                     ew_permi                                                    
                     ssion                                                       
  block_content      move_cus    post-update     Moves the custom block library  
                     tom_bloc                    to Content.                     
                     k_librar                                                    
                     y                                                           
  block_content      sort_per    post-update     Update permissions for users    
                     missions                    with "administer blocks"        
                                                 permission.                     
  editor             image_la    post-update     Enable filter_image_lazy_load   
                     zy_load                     if editor_file_reference is     
                                                 enabled.                        
  file               add_perm    post-update     Grant all non-anonymous roles   
                     issions_                    the 'delete own files'          
                     to_roles                    permission.                     
  masquerade         add_bloc    post-update     Add settings to to masquerade   
                     k_settin                    blocks for link to              
                     g_link                      unmasquerade.                   
  media              oembed_l    post-update     Add the oEmbed loading          
                     oading_a                    attribute setting to field      
                     ttribute                    formatter instances.            
  metatag            remove_r    post-update     Remove 'noydir', 'noodp'        
                     obots_no                    ROBOTS options from meta tag    
                     ydir_noo                    entity fields.                  
                     dp                                                          
  metatag            v2_01_ch    post-update     Convert all fields to use JSON  
                     ange_fie                    storage.                        
                     lds_to_j                                                    
                     son                                                         
  metatag            v2_02_re    post-update     Remove meta tags entity values  
                     move_ent                    that were removed in v2.        
                     ity_valu                                                    
                     es                                                          
  metatag            v2_03_re    post-update     Remove meta tags from default   
                     move_con                    configurations that were        
                     fig_valu                    removed in v2.                  
                     es                                                          
  metatag            v2_04_un    post-update     Uninstall submodule(s)          
                     install_                    deprecated in v2: GooglePlus.   
                     modules                                                     
  metatag            v2_05_tw    post-update     Replace deprecatedremoved       
                     itter_ty                    Twitter Card "type" values.     
                     pe_chang                                                    
                     es                                                          
  responsive_image   image_lo    post-update     Add the image loading settings  
                     ading_at                    to responsive image field       
                     tribute                     formatter instances.            
  responsive_image   order_mu    post-update     Re-order mappings by            
                     ltiplier                    breakpoint ID and descending    
                     _numeric                    numeric multiplier order.       
                     ally                                                        
  slick              changed_    post-update     Clear cache to change           
                     slick_ad                    slick.admin service parameter.  
                     min_serv                                                    
                     ice_para                                                    
                     meter                                                       
  system             enable_p    post-update     Enable the password             
                     assword_                    compatibility module.           
                     compatib                                                    
                     ility                                                       
  system             linkset_    post-update     Add new menu linkset endpoint   
                     settings                    setting.                        
  system             timestam    post-update     Update timestamp formatter      
                     p_format                    settings for entity view        
                     ter                         displays.                       
  views              boolean_    post-update     Update Views config schema to   
                     custom_t                    make boolean custom titles      
                     itles                       translatable.                   
  views              fix_revi    post-update     Fix '-revision_id' replacement  
                     sion_id_                    token syntax.                   
                     part                                                        
  views              oembed_e    post-update     Add eager load option to all    
                     ager_loa                    oembed type field               
                     d                           configurations.                 
  views              responsi    post-update     Add lazy load options to all    
                     ve_image                    responsive image type field     
                     _lazy_lo                    configurations.                 
                     ad                                                          
  views              timestam    post-update     Update timestamp formatter      
                     p_format                    settings for views.             
                     ter                                                         
 ------------------ ----------- --------------- -------------------------------- 


 // Do you wish to run the specified pending updates?: yes.                     

Notice: >  [notice] Update started: az_quickstart_update_10[20](https://github.com/uaz-web/team-tools/actions/runs/6579546880/job/17875925987#step:6:21)801
Notice: >  [notice] Update completed: az_quickstart_update_1020801
Notice: >  [notice] Update started: block_content_update_10100
Notice: >  [notice] Added revision routes to Content block entity type.
Notice: >  [notice] Update completed: block_content_update_10100
Notice: >  [notice] Update started: dblog_update_10100
Notice: >  [notice] Update completed: dblog_update_10100
Notice: >  [notice] Update started: honeypot_update_8101
Notice: >  [notice] Update completed: honeypot_update_8101
Notice: >  [notice] Update started: system_update_10100
Notice: >  [notice] Update completed: system_update_10100
Notice: >  [notice] Update started: az_event_trellis_update_1020801
Notice: >  [notice] Update completed: az_event_trellis_update_1020801
Notice: >  [notice] Update started: az_quickstart_update_1020802
Notice: >  [notice] Update completed: az_quickstart_update_1020802
Notice: >  [notice] Update started: blazy_update_8[21](https://github.com/uaz-web/team-tools/actions/runs/6579546880/job/17875925987#step:6:22)7
Notice: >  [notice] Update completed: blazy_update_8217
Notice: >  [notice] Update started: block_content_update_10200
Notice: >  [notice] Update completed: block_content_update_10200
Notice: >  [notice] Update started: ckeditor_bs_grid_update_9001
Notice: >  [notice] Update completed: ckeditor_bs_grid_update_9001
Notice: >  [notice] Update started: dblog_update_10101
Notice: >  [notice] Update completed: dblog_update_10101
Notice: >  [notice] Update started: history_update_10100
Notice: >  [notice] Update completed: history_update_10100
Notice: >  [notice] Update started: honeypot_update_8102
Notice: >  [notice] Update completed: honeypot_update_8102
Notice: >  [notice] Update started: migrate_update_10100
Notice: >  [notice] Update completed: migrate_update_10100
Notice: >  [notice] Update started: redirect_update_8109
Notice: >  [notice] Update completed: redirect_update_8109
Notice: >  [notice] Update started: slick_update_8210
Notice: >  [notice] Update completed: slick_update_8210
Notice: >  [notice] Update started: az_quickstart_post_update_force_import_core_block_view
Notice: >  [notice] Update completed: az_quickstart_post_update_force_import_core_block_view
Notice: >  [notice] Update started: blazy_post_update_added_blazy_media_service
Notice: >  [notice] Update completed: blazy_post_update_added_blazy_media_service
Notice: >  [notice] Update started: blazy_post_update_added_formatter_blazy_entity
Notice: >  [notice] Update completed: blazy_post_update_added_formatter_blazy_entity
Notice: >  [notice] Update started: block_content_post_update_block_library_view_permission
Notice: >  [notice] Update completed: block_content_post_update_block_library_view_permission
Notice: >  [notice] Update started: block_content_post_update_move_custom_block_library
Notice: >  [notice] Update completed: block_content_post_update_move_custom_block_library
Notice: >  [notice] Update started: block_content_post_update_sort_permissions
Notice: >  [notice] Update completed: block_content_post_update_sort_permissions
Notice: >  [notice] Update started: editor_post_update_image_lazy_load
Notice: >  [notice] Update completed: editor_post_update_image_lazy_load
Notice: >  [notice] Update started: file_post_update_add_permissions_to_roles
Notice: >  [notice] Update completed: file_post_update_add_permissions_to_roles
Notice: >  [notice] Update started: masquerade_post_update_add_block_setting_link
Notice: >  [notice] Update completed: masquerade_post_update_add_block_setting_link
Notice: >  [notice] Update started: media_post_update_oembed_loading_attribute
Notice: >  [notice] Update completed: media_post_update_oembed_loading_attribute
Notice: >  [notice] Update started: metatag_post_update_remove_robots_noydir_noodp
Notice: >  [notice] There were no overridden Metatag records.
Notice: >  [notice] Update completed: metatag_post_update_remove_robots_noydir_noodp
Notice: >  [notice] Update started: metatag_post_update_v2_01_change_fields_to_json
Notice: >  [notice] Processed 8 of 8 overridden Metatag records.
Notice: >  [notice] Update completed: metatag_post_update_v2_01_change_fields_to_json
Notice: >  [notice] Update started: metatag_post_update_v2_02_remove_entity_values
Notice: >  [notice] There were no Metatag records to update.
Notice: >  [notice] Update completed: metatag_post_update_v2_02_remove_entity_values
Notice: >  [notice] Update started: metatag_post_update_v2_03_remove_config_values
Notice: >  [notice] Update completed: metatag_post_update_v2_03_remove_config_values
Notice: >  [notice] Update started: metatag_post_update_v2_04_uninstall_modules
Notice: >  [notice] Metatag: Google Plus is not enabled, nothing to do.
Notice: >  [notice] Update completed: metatag_post_update_v2_04_uninstall_modules
Notice: >  [notice] Update started: metatag_post_update_v2_05_twitter_type_changes
Notice: >  [notice] Update completed: metatag_post_update_v2_05_twitter_type_changes
Notice: >  [notice] Update started: responsive_image_post_update_image_loading_attribute
Notice: >  [notice] Update completed: responsive_image_post_update_image_loading_attribute
Notice: >  [notice] Update started: responsive_image_post_update_order_multiplier_numerically
Notice: >  [notice] Update completed: responsive_image_post_update_order_multiplier_numerically
Notice: >  [notice] Update started: slick_post_update_changed_slick_admin_service_parameter
Notice: >  [notice] Update completed: slick_post_update_changed_slick_admin_service_parameter
Notice: >  [notice] Update started: system_post_update_enable_password_compatibility
Notice: >  [notice] Update completed: system_post_update_enable_password_compatibility
Notice: >  [notice] Batch process has consumed in excess of [60](https://github.com/uaz-web/team-tools/actions/runs/6579546880/job/17875925987#step:6:61)% of available memory. Starting new thread
Notice: >  [notice] Update started: system_post_update_linkset_settings
Notice: >  [notice] Update completed: system_post_update_linkset_settings
Notice: >  [notice] Update started: system_post_update_timestamp_formatter
Notice: >  [notice] Update completed: system_post_update_timestamp_formatter
Notice: >  [notice] Update started: views_post_update_boolean_custom_titles
Notice: >  [notice] Update completed: views_post_update_boolean_custom_titles
Notice: >  [notice] Update started: views_post_update_fix_revision_id_part
Notice: >  [notice] Update completed: views_post_update_fix_revision_id_part
Notice: >  [notice] Update started: views_post_update_oembed_eager_load
Notice: >  [notice] Update completed: views_post_update_oembed_eager_load
Notice: >  [notice] Update started: views_post_update_responsive_image_lazy_load
Notice: >  [notice] Update completed: views_post_update_responsive_image_lazy_load
Notice: >  [notice] Update started: views_post_update_timestamp_formatter
Notice: >  [notice] Update completed: views_post_update_timestamp_formatter
 [success] Finished performing updates.
Notice: ] Command: azs-quickstart.blockview4 -- drush updb [Exit: 0]
```

And that there is only one "Blocks" tab on the admin content dashboard afterwards:
Screenshot 2023-10-19 at 1 47 38 PM

@tadean Also helped me inspect the config snapshots to ensure that the `views.view.block_content` config entity is now owned by the `block_content` module and not associated with `az_quickstart` at all 👍🏻.

**Review by trackleft — APPROVED** [review]

File: az_quickstart.post_update.php [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+  $config_to_import = 'views.view.block_content';
+  $module_path = \Drupal::service('extension.list.module')->getPath('block_content');
+  $config_storage = new FileStorage($module_path . '/config/optional');
+  $entity_type_id = \Drupal::service('config.manager')->getEntityTypeIdByName($config_to_import);
+  /** @var \Drupal\Core\Config\Entity\ConfigEntityStorageInterface $storage */
+  $storage = \Drupal::entityTypeManager()->getStorage($entity_type_id);
+  /** @var \Drupal\Core\Config\Entity\ConfigEntityTypeInterface $entity_type */
+  $entity_type = $storage->getEntityType();
+  $id = $storage->getIDFromConfigName($config_to_import, $entity_type->getConfigPrefix());
+  $active = $storage->load($id);
```
Comment (trackleft) [inline az_quickstart.post_update.php:27]:
```suggestion
  $active = $storage->load($id);
    if (empty($active['_core']['default_config_hash'])) {
      $active'_core']['default_config_hash'] = Crypt::hashBase64(serialize($active));
    }
```

File: az_quickstart.post_update.php [hunk 6]
```diff
@@ -0,0 +1,37 @@
+<?php
+
+/**
+ * @file
+ * Post update functions for AZ Quickstart.
+ */
+
+use Drupal\Core\Config\FileStorage;
```
Comment (trackleft) [inline az_quickstart.post_update.php:8]:
```suggestion
use Drupal\Component\Utility\Crypt;
use Drupal\Core\Config\FileStorage;
```

**Review by trackleft — CHANGES_REQUESTED** [review]
Let's fix the _core: [default_config_hash] before merging.

File: az_quickstart.post_update.php (hunk 6 above)
Comment (tadean) [inline az_quickstart.post_update.php:8]:
```suggestion
use Drupal\Component\Utility\Crypt;
use Drupal\Core\Config\FileStorage;
```

File: az_quickstart.post_update.php [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+  $config_storage = new FileStorage($module_path . '/config/optional');
+  $entity_type_id = \Drupal::service('config.manager')->getEntityTypeIdByName($config_to_import);
+  /** @var \Drupal\Core\Config\Entity\ConfigEntityStorageInterface $storage */
+  $storage = \Drupal::entityTypeManager()->getStorage($entity_type_id);
+  /** @var \Drupal\Core\Config\Entity\ConfigEntityTypeInterface $entity_type */
+  $entity_type = $storage->getEntityType();
+  $id = $storage->getIDFromConfigName($config_to_import, $entity_type->getConfigPrefix());
+  $active = $storage->load($id);
+  $config_record = $config_storage->read($config_to_import);
+
```
Comment (tadean) [inline az_quickstart.post_update.php:29]:
```suggestion

  // Add a config hash if necessary.
  if (empty($config_record['_core']['default_config_hash'])) {
    $config_record['_core']['default_config_hash'] = Crypt::hashBase64(serialize($config_record));
  }

```

Comment (tadean) [reply az_quickstart.post_update.php:29]: @trackleft noticed that when imported this way, the `default_config_hash` is missing, since it seemingly gets added somewhere else in the process normally. This might be one way we could add it in, or maybe there's another function we can use that handles adding it...

Comment (trackleft) [reply az_quickstart.post_update.php:30]: Amzingly, this worked

**Comment by trackleft** [comment]
Amazingly, this appears to have worked 
image

**Comment by trackleft** [comment]
Also, only two errors now 
image

**Review by trackleft — APPROVED** [review]

**Review by tadean — APPROVED** [review]
