### PR TITLE
Closes #892: Reduce paragraphs behavior settings migrate plugin complexity

### LINKED ISSUE #892: Full width text background / full width background wrapper migration needs behavior setting for full width
## Problem/Motivation
Migrating into full width text background doesn't set full width checkbox in text with background.

### Describe the bug
There is a setting for full-width media row, that does a similar thing.
https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php#L90-L92

Setting for text with bg is set here: https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php#L28-L34

## Proposed resolution
In modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
```
    if (!empty($this->configuration['text_background_full_width']) && $row->getSourceProperty($this->configuration['text_background_full_width']) !== FALSE) {
      $behavior['az_text_background_paragraph_behavior']['text_background_full_width'] = $row->getSourceProperty($this->configuration['text_background_full_width']);
    }

```

https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_bg_wrapper.yml#L32
```
text_background_full_width: 'full-width-background'
```

### PR DESCRIPTION
**Pull request by trackleft**
The Paragraphs Behavior migrate process plugin is overly and unnecessarily complex and quickstart paragraph specific.

## Description
In this pull request, I deprecate the existing `paragraphs_behavior_settings` plugin and create a new process plugin called `paragraphs_behavior`

Additionally, I modify existing migrations to use the new plugin.

## Related Issue
Closes #892 

## How Has This Been Tested?
Locally by migrating from a copy of the arizona.edu QS1 site.
See https://97dfa6fc-68bd-4d08-93c6-4b0f4e584f20--site-migration.probo.build/uaqs_flexible_page/no-side-bar-menu-block
See https://kitten.ltrr.arizona.edu/pages/uaqs-flexible-page-2

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+ *     az_text_media_paragraph_behavior:
+ *       bg_color: '@field_uaqs_setting_text_bg_color_processed'
+ *       bg_attach: '@field_uaqs_setting_bg_attach_value'
+ *       position: '@view_mode_processed'
+ *       full_width: '@processed_full_width'
+ *       style: '@content_style_processed'
+ *       az_display_settings:
+ *         bottom_spacing: '@bottom_spacing_processed'
+ *
+ * @endcode * @MigrateProcessPlugin(
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php:65]:
```suggestion
 * @endcode 
 * @MigrateProcessPlugin(
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+ *   id = "paragraphs_behavior"
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php:66]: paragraphs_behavior_settings is already taken, so I welcome any feedback on the id of the plugin.

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+      $plugin_definition,
+      $migration,
+      $container->get('plugin.manager.migrate.process')
+    );
+  }
+
+  /**
+   * {@inheritdoc}
+   */
+  public function transform($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property) {
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php:123]: We could probably get by with just the transform method without `implements ContainerFactoryPluginInterface`
`create` or `__construct`

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml [hunk 4]
```diff
@@ -16,14 +16,13 @@ destination:
...
-      format:  
-        plugin: default_value
-        default_value: az_standard
+    - plugin: sub_process
+      process:
+        delta: delta
+        value: value
+        format:
+          plugin: default_value
+          default_value: az_standard
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml:25]:
```suggestion
    plugin: sub_process
    source: field_uaqs_summary
    process:
      delta: delta
      value: value
      format:  
        plugin: default_value
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php (hunk 3 above)
Comment (joeparsons) [reply modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php:123]: If the parent class already has all the dependencies this plugin needs then, yes, it should be possible to just override the `transform` method.

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php (hunk 2 above)
Comment (joeparsons) [reply modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php:111]: Let's add an `az_` prefix to the ID/machine name please.

Comment (joeparsons) [reply modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php:111]: Maybe `az_paragraphs_behavior_settings` (?)

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml [hunk 5]
```diff
@@ -26,10 +26,16 @@ process:
           source: fid
           migration: 
             - az_media
-
+  gallery_display_processed:
+    plugin: default_value
+    default_value: 'grid'
   behavior_settings:
-    plugin: paragraphs_behavior_settings
-    gallery_display: 'grid'
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml:32]: See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php#L24-L26

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml [hunk 6]
```diff
@@ -26,10 +26,16 @@ process:
...
+    plugin: paragraphs_behavior
+    paragraph_behavior_plugins:
+      az_photo_gallery_paragraph_behavior:
+        gallery_display: '@gallery_display_processed'
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml:36]: See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZPhotoGalleryParagraphBehavior.php#L69

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml [hunk 7]
```diff
@@ -23,7 +23,6 @@ process:
       value: value
       format:  
         plugin: default_value
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml:25]:
```suggestion
        plugin: default_value
        default_value: az_standard
```

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml [hunk 8]
```diff
@@ -49,7 +49,11 @@ process:
         default_value: az_standard
 
   behavior_settings:
-    plugin: paragraphs_behavior_settings
+    plugin: paragraphs_behavior
+    paragraph_behavior_plugins:
+      az_default_paragraph_behavior:
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml:54]: See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_jumbotron.yml [hunk 9]
```diff
@@ -21,7 +21,11 @@ process:
     default_value: az_standard
     
   behavior_settings:
-    plugin: paragraphs_behavior_settings
+    plugin: paragraphs_behavior
+    paragraph_behavior_plugins:
+      az_default_paragraph_behavior:
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_jumbotron.yml:26]: See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_panel_group.yml [hunk 10]
```diff
@@ -55,7 +55,11 @@ process:
             - value
 
   behavior_settings:
-    plugin: paragraphs_behavior_settings
+    plugin: paragraphs_behavior
+    paragraph_behavior_plugins:
+      az_default_paragraph_behavior:
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_panel_group.yml:60]: See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_plain_text.yml [hunk 11]
```diff
@@ -26,7 +26,11 @@ process:
         default_value: az_standard
 
   behavior_settings:
-    plugin: paragraphs_behavior_settings
+    plugin: paragraphs_behavior
+    paragraph_behavior_plugins:
+      az_default_paragraph_behavior:
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_plain_text.yml:31]: See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml [hunk 12]
```diff
@@ -71,13 +71,21 @@ process:
...
+      # field.
+      link_style: 'btn btn-block btn-red'
 
   behavior_settings:
-    plugin: paragraphs_behavior_settings
-    card_width: 'col-md-12 col-lg-12'
-    card_style: 'card'
-    card_width_sm: 'col-sm-12'
-    card_width_xs: 'col-12'
+    plugin: paragraphs_behavior
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml]: See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php#L23-L95
See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php#L113-L166

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml [hunk 13]
```diff
@@ -71,13 +71,21 @@ process:
     plugin: default_value
     default_value:
       class: 'bg-white'
+      # Set the link style to default, since we can't migrate classes to this
```
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml:74]: See https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php#L125

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php [hunk 14]
```diff
@@ -0,0 +1,188 @@
...
+ *       default_value: 'col-md-8 col-lg-6'
+ *   content_style_processed:
+ *     - plugin: default_value
+ *       default_value: 'column'
+ *   bottom_spacing_processed:
+ *     - plugin: default_value
+ *       default_value: 'mb-0'
+ *       source: bottom_spacing
+ *
+ *   #Set the behavior_settings value.
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php:95]:
```suggestion
 *   # Set the behavior_settings value.
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php [hunk 15]
```diff
@@ -0,0 +1,188 @@
...
+ *     s:19:"az_display_settings";a:1:{
+ *       s:14:"bottom_spacing";s:4:"mb-0";
+ *     }
+ *   }
+ * }
+ * ";}
+ *
+ * The `behavior_settings` field uses the `az_paragraphs_behavior_settings`
+ * process plugin to build the array to be serialized, you are able to use the
+ * pseudo field concept within migrate processes to get the values of source
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php:54]:
```suggestion
 * pseudo field concept within migrate processes to get the values of the source
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php [hunk 16]
```diff
@@ -0,0 +1,188 @@
...
+ * @endcode
+ *
+ * @MigrateProcessPlugin(
+ *   id = "az_paragraphs_behavior_settings"
+ * )
+ */
+class AZParagraphsBehaviorSettings extends ProcessPluginBase implements ContainerFactoryPluginInterface {
+
+  /**
+   * The process plugin manager.
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php:117]:
```suggestion
   * The paragraphs behavior plugin manager.
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php [hunk 17]
```diff
@@ -9,8 +9,16 @@
 /**
  * Configure Behavior for paragraphs.
  *
- * @MigrateProcessPlugin(
- *   id = "paragraphs_behavior_settings"
+ * @deprecated in az_quickstart:2.1.3 and is removed from az_quickstart:2.3.0.
+ *   Use the
+ *   \Drupal\az_paragraphs\Plugin\migrate\process\AZParagraphsBehaviorSettings
+ *   process plugin instead following its migration patterns.
+ * // @codingStandardsIgnoreStart
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php:16]:
```suggestion
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php [hunk 18]
```diff
@@ -9,8 +9,16 @@
...
+ * @see https://github.com/az-digital/az_quickstart/pull/1345
+ * @see https://github.com/az-digital/az_quickstart/issues/1348
+ * // @codingStandardsIgnoreEnd
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php:19]:
```suggestion
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php [hunk 19]
```diff
@@ -0,0 +1,188 @@
...
+
+    $behavior = $this->buildSettingsArray($this->configuration['paragraph_behavior_plugins'], $row);
+    $value['behavior'] = serialize($behavior);
+    return $value['behavior'];
+  }
+
+  /**
+   * Recursive array builder that reads values in deeply nested arrays.
+   */
+  protected function buildSettingsArray(array &$settings, Row $row) {
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php:174]:
```suggestion
  protected function buildSettingsArray(array &$settings, Row $row): array {
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php [hunk 20]
```diff
@@ -0,0 +1,188 @@
...
+      $plugin_id,
+      $plugin_definition,
+      $container->get('plugin.manager.paragraphs.behavior')
+    );
+  }
+
+  /**
+   * {@inheritdoc}
+   */
+  public function transform($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property) {
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php:158]:
```suggestion
  public function transform($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property): string {
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php [hunk 21]
```diff
@@ -0,0 +1,188 @@
...
+      }
+    }
+
+    $behavior = $this->buildSettingsArray($this->configuration['paragraph_behavior_plugins'], $row);
+    $value['behavior'] = serialize($behavior);
+    return $value['behavior'];
+  }
+
+  /**
+   * Recursive array builder that reads values in deeply nested arrays.
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php:172]:
```suggestion
   * Recursive array builder that reads values in deeply nested arrays.
   *
   * @param array
   *   The behavior settings array.
   * @param \Drupal\migrate\Row $row
   *   The current row.
   *
   * @return array
   *   The behavior settings array.

```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php [hunk 22]
```diff
@@ -0,0 +1,188 @@
...
+ *         az_display_settings:
+ *           bottom_spacing: '@bottom_spacing_processed'
+ *
+ * @endcode
+ *
+ * @MigrateProcessPlugin(
+ *   id = "az_paragraphs_behavior_settings"
+ * )
+ */
+class AZParagraphsBehaviorSettings extends ProcessPluginBase implements ContainerFactoryPluginInterface {
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php:114]:
```suggestion
class ParagraphsBehaviorSettings extends ProcessPluginBase implements ContainerFactoryPluginInterface {
```

Comment (trackleft) [reply modules/custom/az_paragraphs/src/Plugin/migrate/process/AZParagraphsBehaviorSettings.php:114]: Because we already have an az prefix in the namespace

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php [hunk 23]
```diff
@@ -9,8 +9,14 @@
 /**
  * Configure Behavior for paragraphs.
  *
- * @MigrateProcessPlugin(
- *   id = "paragraphs_behavior_settings"
+ * @deprecated in az_quickstart:2.1.3 and is removed from az_quickstart:2.3.0.
+ *   Use the
+ *   \Drupal\az_paragraphs\Plugin\migrate\process\AZParagraphsBehaviorSettings
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php:14]:
```suggestion
 *   \Drupal\az_paragraphs\Plugin\migrate\process\ParagraphsBehaviorSettings
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php [hunk 24]
```diff
@@ -9,8 +9,14 @@
...
+ *   process plugin instead following its migration patterns.
+ * @see https://github.com/az-digital/az_quickstart/pull/1345
+ * @see https://github.com/az-digital/az_quickstart/issues/1348
+ *
+ * @MigrateProcessPlugin( id = "paragraphs_behavior_settings"
```
Comment (joeparsons) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php:19]:
```suggestion
 * @MigrateProcessPlugin(
 *   id = "paragraphs_behavior_settings"
```

**Review by joeparsons — COMMENTED** [review]
Various comment / coding standards fixes.

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php [hunk 25]
```diff
@@ -9,8 +9,14 @@
 /**
  * Configure Behavior for paragraphs.
  *
- * @MigrateProcessPlugin(
- *   id = "paragraphs_behavior_settings"
+ * @deprecated in az_quickstart:2.1.3 and is removed from az_quickstart:2.3.0.
+ *   Use the
+ *   \Drupal\az_paragraphs\Plugin\migrate\process\AZParagraphsBehaviorSettings
+ *   process plugin instead following its migration patterns.
```
Comment (joeparsons) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php:15]: Maybe we could just use the ID in this comment?
```suggestion
 *
 * Use the az_paragraphs_behavior_settings process plugin instead following its
 * migration patterns.
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php [hunk 26]
```diff
@@ -9,8 +9,14 @@
...
+ * @see https://github.com/az-digital/az_quickstart/pull/1345
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php:16]:
```suggestion
* // @codingStandardsIgnoreStart
 * @see https://github.com/az-digital/az_quickstart/pull/1345
```

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php [hunk 27]
```diff
@@ -9,8 +9,14 @@
...
+ * @see https://github.com/az-digital/az_quickstart/issues/1348
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php:17]:
```suggestion
 * @see https://github.com/az-digital/az_quickstart/issues/1348
 * // @codingStandardsIgnoreEnd
```

**Review by danahertzberg — APPROVED** [review]

File: modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php [hunk 28]
```diff
@@ -9,6 +9,15 @@
 /**
  * Configure Behavior for paragraphs.
  *
+ * @deprecated in az_quickstart:2.1.3 and is removed from az_quickstart:2.3.0.
```
Comment (trackleft) [inline modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php:12]:
```suggestion
 * @deprecated in az_quickstart:2.2.0 and is removed from az_quickstart:2.3.0.
```

**Review by joeparsons — DISMISSED** [review]
I'd be in favor of including this in the new minor release (2.2.x only)

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml [hunk 29]
```diff
@@ -68,6 +68,9 @@ process:
         plugin: default_value
         default_value:
           class: 'bg-white'
+          # Set the link style to default, since we can't migrate classes to this
+          # field.
+          link_style: 'btn btn-block btn-red'
```
Comment (danahertzberg) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml:73]: This is no longer the default link style (it's a plain text link now)

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml [hunk 30]
```diff
@@ -83,14 +86,49 @@ process:
           migration:
             - az_media
 
+  card_width_processed:
+    plugin: default_value
+    default_value: 'col-md-4 col-lg-4'
```
Comment (danahertzberg) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml:91]: I also believe this is the new default (Cards per row on tablet is set to 1)
```suggestion
    default_value: 'col-lg-4'
```

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml [hunk 31]
```diff
@@ -71,13 +71,21 @@ process:
...
+      # field.
```
Comment (danahertzberg) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml:75]: Should this be on the previous line?

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml [hunk 32]
```diff
@@ -71,13 +71,21 @@ process:
...
+      link_style: 'btn btn-block btn-red'
```
Comment (danahertzberg) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml:76]: Change to new default text link

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml (hunk 31 above)
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml:75]:
```suggestion
      # Set the link style to default, since we can't migrate classes to this field.
```

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml (hunk 32 above)
Comment (trackleft) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml:76]:
```suggestion
      link_style: 'btn-block'
```

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml (hunk 29 above)
Comment (danahertzberg) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml:73]:
```suggestion
          link_style: 'btn-block'
```

File: modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml [hunk 33]
```diff
@@ -68,6 +68,9 @@ process:
         plugin: default_value
         default_value:
           class: 'bg-white'
+          # Set the link style to default, since we can't migrate classes to this
+          # field.
```
Comment (danahertzberg) [inline modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml:72]:
```suggestion
          # Set the link style to default, since we can't migrate classes to this field.
```

**Review by danahertzberg — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]
The migrated paragraphs on the flexible pages in the Probo migration test site looked considerably better than on other PRs before the build was reaped.
