### PR TITLE
Closes #5507: Clear plugin definition cache on enterprise attributes settings save

### LINKED ISSUE #5507: Cache not cleared when migration endpoint settings are saved, causing stale API URLs
## Describe the bug

When an admin updates an API endpoint URL in migration settings (e.g. **Enterprise Attributes Importer Settings** or **Course Importer Settings**), the change does not take effect until a manual cache clear is performed.

## Affected modules
| Module | Settings form | Config key | What's injected |
|---|---|---|---|
| `az_enterprise_attributes_import` | Enterprise Attributes Importer Settings | `az_enterprise_attributes_import.settings` → `endpoint` | Source URL |

Claude found these other potential ones... since this kind of thing affects any module using `hook_migration_plugins_alter()` to inject config values into migration plugin definitions. Drupal caches migration plugin definitions, so saving a new URL updates the config but does not invalidate the plugin cache — subsequent migration would run silently continue using the old URL.

1. `az_course`, `CourseImportForm.php`::`submitForm()`
2. `az_http`, `AZHttpSettingsForm.php`::`submitForm()`

But after double checking, these both have `drupal_flush_all_caches()` already, so these should be good

## Steps to reproduce (enterprise attributes example)

1. Go to any Quickstart site with Enterprise Attributes; usually it will have this  **live** URL:
   - Live: `https://api.trellis.arizona.edu/ws/rest/events/v1/enterprise-attributes`
2. Go to Configuration -> Arizona Quickstart Settings -> Enterprise Attributes Import. 
3. Change endpoint to a different URL like say a **dev** version:
   - Dev: `https://api.qa.trellis.arizona.edu/ws/rest/events/v1/enterprise-attributes` (At the time of this issue's writing, this API includes `Program_Type__c`, which is not available in live)
4. Click Save Configuration. It will attempt to Import (Equivalent to `drush migrate:import az_enterprise_attributes_import`) but it will still fetches from the old URL, which in this case is Live, which only has 194 terms
5. Clear cache (drush cr). Go to Step 2 and click on Save Configuration again — now it fetches from **dev**, 211 terms imported correctly

## Expected behavior

Saving any migration settings form should immediately invalidate the plugin definition cache so the new values are used on the next migration run without requiring a manual cache clear.

## Proposed fix

In each affected settings form's `submitForm()`, call:

```php
\Drupal::service('plugin.cache_clearer')->clearCachedDefinitions();

### PR DESCRIPTION
**Pull request by kevdevlu**
Closes #5507 

## Description

Adds clearCachedDefinitions() after config save so migration runs immediately pick up the new endpoint without requiring a manual drush cr.

## How to test

1. Enable `Quickstart Enterprise Attributes Import` module
2. Go to Arizona Quickstart Settings, then Enterprise Attributes Settings tab: `/admin/config/az-enterprise-attributes-import/settings`
3. Click on `Save Configuration`. It should say `Processed 195 items (0 created, 194 updated, 0 failed, 1 ignored) - done with 'az_enterprise_attributes_import'`
4. Now change the URL to the new dev (about to be prod) version: `https://api.qa.trellis.arizona.edu/ws/rest/events/v1/enterprise-attributes`  (note the diff: `...api.qa.trellis...`)
5. There should be 212 items processed now. 
6. Go to Structure -> Taxonomy -> Enterprise Attributes -> List Terms. at `/admin/structure/taxonomy/manage/az_enterprise_attributes/overview` and make sure `Program Type` is included (which was not there before)

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

File: modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php [hunk 1]
```diff
@@ -98,6 +98,8 @@ public function submitForm(array &$form, FormStateInterface $form_state) {
       ->set('endpoint', $form_state->getValue('endpoint'))
       ->save();
```
Comment (tadean) [inline modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php:109]: It seems like maybe this should inject the service rather than calling it statically.

Comment (kevdevlu) [reply modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php:109]: Thanks!

**Review by joeparsons — DISMISSED** [review]

File: modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php [hunk 2]
```diff
@@ -45,6 +46,13 @@ class AZEnterpriseAttributesImportForm extends ConfigFormBase {
    */
   protected TranslationInterface $translation;
 
+  /**
+   * The plugin cache clearer.
+   *
+   * @var \Drupal\Core\Plugin\CachedDiscoveryClearer
+   */
+  protected CachedDiscoveryClearer $pluginCacheClearer;
```
Comment (tadean) [inline modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php]: Perhaps `CachedDiscoveryClearerInterface` rather than `CachedDiscoveryClearer`?

File: modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php [hunk 3]
```diff
@@ -6,6 +6,7 @@
 use Drupal\Core\Form\ConfigFormBase;
 use Drupal\Core\Form\FormStateInterface;
 use Drupal\Core\KeyValueStore\KeyValueFactoryInterface;
+use Drupal\Core\Plugin\CachedDiscoveryClearer;
```
Comment (tadean) [inline modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php]:
```suggestion
use Drupal\Core\Plugin\CachedDiscoveryClearerInterface;
```

File: modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php [hunk 4]
```diff
@@ -45,6 +46,13 @@ class AZEnterpriseAttributesImportForm extends ConfigFormBase {
    */
   protected TranslationInterface $translation;
 
+  /**
+   * The plugin cache clearer.
+   *
+   * @var \Drupal\Core\Plugin\CachedDiscoveryClearer
```
Comment (tadean) [inline modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php]:
```suggestion
   * @var \Drupal\Core\Plugin\CachedDiscoveryClearerInterface
```

File: modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php (hunk 2 above)
Comment (tadean) [inline modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php]:
```suggestion
  protected CachedDiscoveryClearerInterface $pluginCacheClearer;
```

**Review by joeparsons — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Comment by tadean** [comment]
Worked successfully in local testing, thanks @kevdevlu !
