### PR TITLE
Closes #1697: Fix JS error when Text with Background, Text on Media are not full-width

### LINKED ISSUE #1697: JavaScript error when Text with Background, Text on Media not set to full width
## Problem/Motivation
I noticed a JavaScript error in the Chrome DevTools console that is related to code we implemented to push sidebars down below the last full-width paragraph. 

### Describe the bug
When Text with Background or Text on Media paragraphs are added to a page but none are set to full width, when the page is loaded the pushSidebarsDown function in az_paragraphs_full_width.js in attempts to read the currentStyle property of the first item of the allFullWidthElements array. However, in this case the allFullWidthElements array is empty, so an error is thrown.

### To Reproduce

1. Create a page with one or more Text with Background or Text on Media paragraphs. Make sure none of those paragraphs are set to full width.
2. Visit the page
3. Open Chrome DevTools and note the Uncaught TypeError message(s)

## Proposed resolution
Modify the Text with Background and Text on Media paragraph behaviors so that the pushSidebarsDown function will not be called if they are not full-width.

### Expected behavior

The pushSidebarsDown function should not be executed if there are no full-width paragraphs in the main content of the page.

##  Screenshots
Console error message:
image

### Desktop (please complete the following information):
 - OS: macOS 12.4
 - Browser: Chrome v102

### PR DESCRIPTION
**Pull request by bberndt-uaz**
## Description

This PR fixes the JavaScript error that occurs when Text with Background or Text on Media paragraphs are added to a page but none are set to full width by doing the following:
- Remove the az_paragraphs.az_paragraphs_full_width library as a dependency for Text with Background and Text on Media
- Update the preprocess function for Text with Background and Text on Media to attach the az_paragraphs.az_paragraphs_full_width library only if the paragraph is set to be full-width.
- Add a test to az_paragraphs_full_width.js to exit the pushSidebarsDown function if there are no full-width elements in the content region.

## Related issues

#1697 

## How to test

1. Create a page with one or more Text with Background or Text on Media paragraphs. Make sure none of those paragraphs are set to full width.
2. Visit the page
3. Open Chrome DevTools and note that there are no more Uncaught TypeError message(s) regarding the currentStyle property

Tested locally and in Probo.

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [X] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php [hunk 1]
```diff
@@ -120,6 +120,11 @@ public function preprocess(&$variables) {
     // Get plugin configuration and save in vars for twig to use.
     $config = $this->getSettings($paragraph);
 
+    // If this paragraph is full-width, add the full-width library.
+    if (isset($config['text_background_full_width'])) {
```
Comment (joeparsons) [inline modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php:124]: I think it'd be better to check for the actual value here.
```suggestion
    if (isset($config['text_background_full_width']) && $config['text_background_full_width'] === 'full-width-background') {
```

File: modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php [hunk 2]
```diff
@@ -236,6 +236,11 @@ public function preprocess(&$variables) {
       HTML::getClass($config['style']),
     ];
 
+    // If this paragraph is full-width, add the full-width library.
+    if (isset($config['text_background_full_width'])) {
```
Comment (joeparsons) [inline modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php:240]: I think it'd be better to check for the actual value here.
```suggestion
    if (isset($config['text_background_full_width']) && $config['text_background_full_width'] === 'full-width-background') {
```

**Review by trackleft — APPROVED** [review]
This is lovely

**Review by joeparsons — APPROVED** [review]

**Review by tadean — APPROVED** [review]
