### PR TITLE
Fixes #2201 Custom form display disabled on module uninstall.

### LINKED ISSUE #2201: Custom fields on AZ content types get disabled on form display with any module uninstall
## Problem/Motivation
A site builder may want to add custom fields to AZ content types with the UI since it is a common and available UI workflow. When any module is uninstalled, those custom fields are removed from the content type form display and placed into the disabled section.

### Describe the bug
Uninstalling modules disables custom AZ content type fields on the form display.

This issue does not occur on non-AZ custom content types.

### To Reproduce

1. Go to Structure > edit People
2. Add any custom field (e.g., Publications using Text formatted, long).
3. Go to Manage form display and observe the new custom field in the 'active' list of fields.
4. Install a module (e.g., masquerade, devel, etc.)
5. Uninstall a module.
6. Return to the People content type's Manage form display and observe the new custom field in the 'disable' section.

### Expected behavior
Uninstalling a module should not disable custom fields on AZ content type form displays.

### PR DESCRIPTION
**Pull request by tadean**
## Description
Currently when modules are disabled in Quickstart, customized entity form displays are being reverted, causing custom fields to become hidden on entity forms. This is a symptom of the fact that Quickstart configuration override modules are reapplying their override each time a module was uninstalled.

Our configuration provider uses the `listConfig()` function to gather information about changing module configuration to know what configuration may need overrides enabled, and when no modules are selected (e.g. no new modules is enabled), it returns all configuration rather than no configuration; this lead to our provider reapplying its overrides on every module uninstall. This PR puts in place a check to make sure the list of extensions isn't an empty array to prevent this.

Additionally, there is the more general problem that the configuration override system probably should not override things unless it is safe to. This PR puts in place a check that `diffs` the configuration of the active site and the last known configuration snapshot of a distribution module. Overrides are only allowed if the active configuration of a module is unchanged. This means overrides will no longer be applied if the configuration entity in the override is customized on the active site.

## Related issues
#2201 

## How to test

- Make a change to an entity form display for a quickstart content type, e.g. adding a new custom field to `az_person`
- disable a module
- verify the custom field is still in the person display
- disable `az_cas`
- make a change to the `cas` settings
- enable `az_cas`
- check the drupal log for warning that the override was ignored due to customizations (`Disallowing override of customized configuration`)

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [x] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [x] New feature
   - [x] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by camikazegreen** [comment]
I tried to test this, but wasn't able to reproduce the original error on a site prior to this fix.

File: modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php [hunk 1]
```diff
@@ -245,6 +287,16 @@ public function getOverrideConfig(array $extensions = [], array $old_extensions
       $value = $this->addDefaultConfigHash($value);
       if (!$this->validateDependencies($name, $data, $enabled_extensions, $all_config)) {
         // Couldn't validate dependency.
+        \Drupal::logger('az_core')->notice("Could not validate dependences of override @name.", [
```
Comment (bberndt-uaz) [inline modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php:290]:
```suggestion
        \Drupal::logger('az_core')->notice("Could not validate dependencies of override @name.", [
```

**Review by trackleft — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Comment by joshuasosa** [comment]
Just wanted to follow up and confirm that this change did fix the issue for me. Thanks! Very helpful!

**Comment by tadean** [comment]
Excellent! Thanks for reporting this, and all your testing about the issue @joshuasosa !
