### PR TITLE
Close #4604 Address issues found by ESLint CI Job

### LINKED ISSUE #4604: Address issues found by ESLint automated check.
## Problem/Motivation
Why the issue was filed, steps to reproduce the problem, etc.

### Describe the bug
While watching automated tests, I noticed the following errors.
```
<div class="mt-1 mb-3 px-3" style="box-sizing: border-box; margin-top: 4px !important; margin-bottom: 16px !important; padding-right: 16px !important; padding-left: 16px !important; color: rgb(31, 35, 40); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mx-0 mx-md-1" style="box-sizing: border-box; margin-right: 4px !important; margin-left: 4px !important;"><h2 class="text-bold h4" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 16px !important; font-weight: 600 !important;">Annotations</h2><div class="color-fg-muted text-small" style="box-sizing: border-box; color: rgb(89, 99, 110) !important; font-size: 12px !important;">16 warnings</div></div></div>
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L12[no-console] Unexpected console statement.
--
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L15[no-console] Unexpected console statement.
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L18[no-console] Unexpected console statement.
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L120[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L132[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L11[func-names] Unexpected unnamed function.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L17[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L20[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L23[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L27[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L30[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L33[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L36[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L39[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L42[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
modules/custom/az_select_menu/js/az-select-menu.es6.js#L45[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.

Annotations
16 warnings
[modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L12](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245116)
[no-console] Unexpected console statement.
[modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L15](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245118)
[no-console] Unexpected console statement.
[modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L18](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245121)
[no-console] Unexpected console statement.
[modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L120](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245125)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js#L132](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245131)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L11](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245134)
[func-names] Unexpected unnamed function.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L17](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245141)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L20](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245147)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L23](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245151)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L27](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245154)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L30](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245156)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L33](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245159)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L36](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245160)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L39](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245162)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L42](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245164)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
[modules/custom/az_select_menu/js/az-select-menu.es6.js#L45](https://github.com/az-digital/az_quickstart/commit/894739251401ee9e3346f3856c1c459a6815993e#annotation_37432245167)
[max-nested-callbacks] Too many nested callbacks (4). Maximum allowed is 3.
```
### To Reproduce

Go to https://github.com/az-digital/az_quickstart/actions/runs/16738104573

## Proposed resolution

Address all eslint warnings.

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Refactors and tidies JS to address ESLint warnings from #4604:
- **Vimeo (text+media) behavior**: extracts small helpers for play/pause handlers, single‑element initialization, and API‑loaded callback to reduce nesting; keeps logic identical while improving readability and testability. Adds `// eslint-disable-next-line no-console` for the three diagnostic `console.log` calls flagged by the action. Files:  
  - `modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js`  
  - Built output: `.../az_paragraphs_az_text_media_vimeo.js`
- **Full‑width layout**: minor clarity tweak when reading sidebar width before setting `--full-width-sidebar-width`.  
  - `modules/custom/az_paragraphs/js/az_paragraphs_full_width.js`
- **Select menu**: introduces small helper functions to attach element, button, and document event listeners and route events through `Drupal.azSelectMenu.handleEvents`, reducing nested callbacks and unnamed functions.  
  - `modules/custom/az_select_menu/js/az-select-menu.es6.js`

These changes resolve the specific ESLint rules noted in the failing run (e.g., `no-console`, `max-nested-callbacks`, `func-names`) without altering user‑facing behavior.  #4604

## Related issues
- Fixes #4604

## How to test
1. **Lint passes**  
   - Push this branch or re‑run the workflow for the branch and confirm the ESLint job completes without warnings for the files referenced in #4604.  [oai_citation:3‡GitHub](https://github.com/az-digital/az_quickstart/issues/4604)
   - (Optional, local) Run the repo’s JS lint script if available (e.g., `npm ci && npm run lint`) and verify no errors/warnings in the changed files.
2. **Vimeo paragraph regression check**  
   - Create a “Text + Media (Vimeo)” paragraph with a valid Vimeo ID.  
   - Verify play/pause buttons still start/stop video and toggle `.az-video-playing` / `.az-video-paused` on the parent element.  
   - Resize the viewport; confirm the player is sized via `setDimensions()` after `bufferend` as before.
3. **Select menu regression check**  
   - Visit a page that uses the AZ select menu.  
   - Verify popover still initializes and interactions (focus, mouseenter, change, click) continue to call `Drupal.azSelectMenu.handleEvents`.
4. **Full‑width layout check**  
   - On a page with a sidebar, ensure the CSS custom property `--full-width-sidebar-width` is still set to the sidebar’s width and layout remains unchanged.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [x] Accessibility, performance, or security improvement (tooling/code quality)
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

File: modules/custom/az_event/js/az_calendar_filter.js [hunk 1]
```diff
@@ -145,4 +145,4 @@
       });
     }
   };
-})(jQuery, Drupal, drupalSettings, once);
+})(jQuery, Drupal, drupalSettings, once);
```
Comment (trackleft) [inline modules/custom/az_event/js/az_calendar_filter.js:148]:
```suggestion
})(jQuery, Drupal, drupalSettings, once);

```

**Comment by joeparsons** [comment]
The most recent eslint/glob version changes were introduced in #4427, so I think we'll want backport this to 2.x as well.

**Review by joeparsons — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Review by bberndt-uaz — APPROVED** [review]
