### PR TITLE
Closes #1225: Removing setting the class array as a string everywhere, and fixing bottom spacing issue.

### LINKED ISSUE #1225: Text on Media PHP error: [] operator not supported for strings
### Describe the bug
On the most recent version of Quickstart 2.0 (2.0.13), the following PHP error occurs after save when you add a Text on Media component to a Flexible Page.

```
Error: [] operator not supported for strings in Drupal\az_paragraphs\Plugin\paragraphs\Behavior\AZTextWithMediaParagraphBehavior->view() (line 260 of /code/web/profiles/custom/az_quickstart/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php)
```

### To Reproduce

1. Create a Flexible Page
2. Add a Text on Media component and fill out all the fields
3. Save the page

Upon save, you should see the error.

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Attributes class arrays should always be arrays and never strings.

## Related Issue
Closes #1225 

## How Has This Been Tested?
Probo
Go to text on media page, add margin bottom to one of the paragraphs, and it still works.
Go to theme settings and upload SVG and mark that it should be rendered inline, with  `qs-logo-svg-inline` class

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php [hunk 1]
```diff
@@ -179,9 +177,6 @@ public function preprocess(&$variables) {
     }
     $paragraph_status = $paragraph->status->value ? 'published' : 'unpublished';
     $variables['attributes']['id'] = HTML::getId($paragraph->bundle() . '-' . $paragraph->id());
-    if (!empty($variables['attributes']) && !empty($variables['attributes']['class']) && !is_array($variables['attributes']['class'])) {
-      $variables['attributes']['class'] = [];
-    }
     $variables['attributes']['class'][] = 'paragraph';
```
Comment (joeparsons) [inline modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php:180]: We could also do something like this to ensure `$variables['attributes']['class']` is an array without blowing away its existing value:

```suggestion
    if (!empty($variables['attributes']) && !empty($variables['attributes']['class']) && !is_array($variables['attributes']['class'])) {
      $variables['attributes']['class'] = [$variables['attributes']['class']];
    }
    $variables['attributes']['class'][] = 'paragraph';
```

**Review by joeparsons — APPROVED** [review]
Looks good to me.

**Comment by bberndt-uaz** [comment]
Tested in Probo:
- Added/removed margin bottom to paragraphs on Text on Media page and confirmed that the page was updated correctly. 
- Replaced the footer logo with an uploaded SVG,  confirmed that it has the qs-logo-svg-inline class.

**Review by bberndt-uaz — APPROVED** [review]

File: themes/custom/az_barrio/az_barrio.theme [hunk 2]
```diff
@@ -470,7 +470,7 @@ function az_barrio_footer_logo() {
       $svg = file_get_contents($filepath);
       $rendered_image = render($svg);
       $image_markup = Markup::create($rendered_image);
-      $attr['attributes']['class'] = 'qs-logo-svg-inline';
+      $attr['attributes']['class'][] = 'qs-logo-svg-inline';
       // Footer link destination is empty (default value)
```
Comment (trackleft) [inline themes/custom/az_barrio/az_barrio.theme:474]: qs-logo-svg-inline is marked as an experimental feature FWIW
