### PR TITLE
Fixes #4263 Course Import Instructions

### LINKED ISSUE #4263: Course Import Instructions (and Rules) are Unclear
## Problem/Motivation
Uncovered during Minor Release testing for 2.9, though issues predated this.  Issue was forgotten until 2.13 testing when it was uncovered again.

### Describe the bug

Two issues: import restrictions & unclear instructions

1. It seems like there is something restricting some courses from being imported, but that restriction is not transparent to the user
- See "To Reproduce" below"
- Conversation about this on Slack with lots of details, examples and speculation: https://uarizona.slack.com/archives/C9EDC2RDM/p1704840217076589

2. Instructions on importing courses on this page are unclear: /admin/config/az-quickstart/courses

- Do courses need to be in quotes (i.e. "ARC 330") or not? 
- Instructions reference "push Import Courses button" - but there is no button that matches this description

### To Reproduce

For issue #1 above:
- Go to /admin/config/az-quickstart/courses
- Import the following:

ARC 330
ARC 459

Notice only one course is imported (ARC 330).

[This link shows course availability](https://studentcenter.arizona.edu/app/ui/public/ps/course-catalog?tab=DEFAULT), but that info is confusing:
- Both courses above not shown as offered Spring 2025
- Both courses above are shown under Fall 2025 as offered in Spring

Based on the above, I can't figure out why ARC 459 is skipped. 

## Proposed resolution

Provide clear instructions to user when adding courses for import
Prep user to understand why certain courses may not import, or provide notice after import as to why a course did not import

### Expected behavior

Any course should import, and terms available should be shown on course, rather than preventing course from being imported. 

##  Screenshots

See video in Slack link above

### PR DESCRIPTION
**Pull request by tadean**
This PR provides additional instructions on the import page for `az_course`.

- Some instructions are given as to how the form functions
- A placeholder attribute is added showing expected format
- Warn users about the potential for timeouts and mention the potential solution of `drush` or `az_http`
- give each submit button a title attribute that describes what it does

image

## Related issues
#4263 

## How to test

- enable `az_course` and `az_http`
- visit `/admin/config/az-quickstart/courses`
- review form changes for usability or documentation issues
- test that form functions as expected

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [x] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Review by joeparsons — DISMISSED** [review]

**Review by danahertzberg — APPROVED** [review]

File: modules/custom/az_course/src/Form/CourseImportForm.php [hunk 1]
```diff
@@ -82,36 +82,70 @@ public function buildForm(array $form, FormStateInterface $form_state) {
...
+        $this->t('Running the <strong>az_courses</strong> migration via <strong>Drush</strong> will also import these configured courses.'),
+        $this->t('At least one scheduled section of a course must exist in an active term in order to be imported.'),
+      ],
+    ];
+
     $form['courses'] = [
       '#type' => 'textarea',
       '#title' => $this->t('Courses to Import'),
-      '#description' => $this->t('Courses will be imported when az_courses migration is run either by drush or pushing the "Import Courses" button. List courses to import, one per line, in format "ENGL 101" or "ENGL" for entire subject.'),
+      '#description' => $this->t('. List courses to import, one per line, in format <strong>ENGL 101</strong> or <strong>ENGL</strong> for an entire subject. At least one scheduled section of the course must exist in an active term to be imported.'),
```
Comment (danahertzberg) [inline modules/custom/az_course/src/Form/CourseImportForm.php:106]:
```suggestion
      '#description' => $this->t('List courses to import, one per line, in format <strong>ENGL 101</strong> or <strong>ENGL</strong> for an entire subject. At least one scheduled section of the course must exist in an active term to be imported.'),
```

Comment (tadean) [inline modules/custom/az_course/src/Form/CourseImportForm.php:106]:
```suggestion
      '#description' => $this->t('List courses to import, one per line, in format <strong>ENGL 101</strong> or <strong>ENGL</strong> for an entire subject. At least one scheduled section of the course must exist in an active term to be imported.'),
```

**Review by danahertzberg — APPROVED** [review]
